// Shipping capacity dashboard. Consumes the static snapshot generated by
// scripts/shipping_capacity/build_snapshot.py; no API key is exposed here.
(() => {
    const DATA_URL = '/public/data/shipping_capacity_v1.json';
    const VIEW_META = {
        shipping_fleet: {
            eyebrow: 'GLOBAL FLEET',
            title: '글로벌 선대',
            desc: 'UNCTAD 관측 기준으로 세계 상선 선복량과 선종별 구성을 확인합니다.'
        },
        shipping_routes: {
            eyebrow: 'ROUTE CAPACITY',
            title: '항로별 선복량',
            desc: '연간 화물톤과 왕복 운항주기로 항로에 묶이는 필요 선복량을 추정합니다.'
        },
        shipping_chokepoints: {
            eyebrow: 'CHOKEPOINT MONITOR',
            title: '초크포인트 모니터',
            desc: 'IMF PortWatch 최근 7일 통항 capacity를 직전 28일 기준선과 비교합니다.'
        },
        shipping_scenarios: {
            eyebrow: 'SHOCK SIMULATOR',
            title: '봉쇄 충격 시뮬레이터',
            desc: '봉쇄율과 기간을 바꿔 우회·대기·취소가 선복량에 미치는 영향을 계산합니다.'
        },
        shipping_environment: {
            eyebrow: 'REGULATORY OUTLOOK',
            title: '환경규제 시뮬레이터',
            desc: 'IMO CII · EU ETS · FuelEU Maritime 대응 시나리오별 유효 선복량 손실을 확인합니다.'
        }
    };
    const VIEW_ORDER = [
        ['shipping_fleet', '글로벌 선대'],
        ['shipping_routes', '항로별 선복량'],
        ['shipping_chokepoints', '초크포인트'],
        ['shipping_scenarios', '봉쇄 시뮬레이터'],
        ['shipping_environment', '환경규제']
    ];
    const SHIP_TYPE_LABELS = {
        dry_bulk: '벌크선',
        tanker: '유조선',
        container: '컨테이너선',
        general_cargo: '일반화물선',
        other: '기타 선박'
    };
    const SHIP_TYPE_COLORS = {
        dry_bulk: '#38bdf8',
        tanker: '#818cf8',
        container: '#22c55e',
        general_cargo: '#f59e0b',
        other: '#64748b'
    };

    let dataPromise = null;
    let activeCharts = [];

    const escapeHtml = value => String(value ?? '')
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#039;');

    const formatNumber = (value, digits = 0) => Number(value || 0).toLocaleString('ko-KR', {
        minimumFractionDigits: digits,
        maximumFractionDigits: digits
    });

    const formatDwt = value => {
        const number = Number(value || 0);
        if (number >= 1e9) return `${(number / 1e9).toFixed(2)}B DWT`;
        if (number >= 1e6) return `${(number / 1e6).toFixed(1)}M DWT`;
        if (number >= 1e3) return `${(number / 1e3).toFixed(0)}K DWT`;
        return `${formatNumber(number)} DWT`;
    };

    const formatTonnes = value => {
        const number = Number(value || 0);
        if (number >= 1e9) return `${(number / 1e9).toFixed(2)}B t`;
        if (number >= 1e6) return `${(number / 1e6).toFixed(1)}M t`;
        if (number >= 1e3) return `${(number / 1e3).toFixed(0)}K t`;
        return `${formatNumber(number)} t`;
    };

    const formatPct = (value, digits = 1) => `${Number(value || 0).toFixed(digits)}%`;

    const formatReferenceSize = size => {
        if (!size) return '설정 없음';
        if (size.teu_min) return `${formatNumber(size.teu_min / 1000, 0)}K–${formatNumber(size.teu_max / 1000, 0)}K TEU`;
        if (size.dwt_min) return `${formatNumber(size.dwt_min / 1000, 0)}K–${formatNumber(size.dwt_max / 1000, 0)}K DWT`;
        return '설정 없음';
    };

    const formatDate = value => {
        if (!value) return '업데이트 없음';
        const parsed = new Date(value);
        return Number.isNaN(parsed.getTime()) ? escapeHtml(value) : parsed.toLocaleDateString('ko-KR');
    };

    const destroyCharts = () => {
        activeCharts.forEach(chart => {
            try { chart.destroy(); } catch (_) { /* chart already removed */ }
        });
        activeCharts = [];
    };

    const createChart = (root, canvasId, config) => {
        const canvas = root.querySelector(`#${canvasId}`);
        if (!canvas || typeof Chart === 'undefined') return null;
        const existing = Chart.getChart(canvas);
        if (existing) existing.destroy();
        const chart = new Chart(canvas, config);
        activeCharts.push(chart);
        return chart;
    };

    const loadData = () => {
        if (!dataPromise) {
            dataPromise = fetch(DATA_URL, { cache: 'no-cache' }).then(async response => {
                if (!response.ok) throw new Error(`선복량 데이터 응답 오류 (${response.status})`);
                const payload = await response.json();
                if (payload.schema_version !== 'shipping-capacity-v1') {
                    throw new Error('지원하지 않는 선복량 데이터 버전입니다.');
                }
                return payload;
            }).catch(error => {
                dataPromise = null;
                throw error;
            });
        }
        return dataPromise;
    };

    const sourceLink = data => {
        const source = data.sources?.[0];
        if (!source) return '';
        return `<a class="shipping-source-link" href="${escapeHtml(source.url)}" target="_blank" rel="noopener">UNCTAD 원문 ↗</a>`;
    };

    const shell = (data, target, content) => {
        const meta = VIEW_META[target] || VIEW_META.shipping_fleet;
        const tabs = VIEW_ORDER.map(([id, label]) => `
            <button type="button" class="shipping-tab ${id === target ? 'active' : ''}" data-shipping-view="${id}">
                ${label}
            </button>
        `).join('');
        return `
            <div class="shipping-shell">
                <section class="shipping-hero">
                    <div>
                        <p class="shipping-eyebrow">${meta.eyebrow}</p>
                        <h1>${meta.title}</h1>
                        <p class="shipping-hero-desc">${meta.desc}</p>
                    </div>
                    <div class="shipping-hero-meta">
                        <span class="shipping-badge observed">관측 + 추정 분리</span>
                        <span>생성 ${formatDate(data.generated_at)}</span>
                        ${sourceLink(data)}
                    </div>
                </section>
                <nav class="shipping-tabs" aria-label="해운 데이터 화면">${tabs}</nav>
                <main class="shipping-content">${content}</main>
            </div>
        `;
    };

    const bindInternalNavigation = root => {
        root.querySelectorAll('[data-shipping-view]').forEach(button => {
            button.addEventListener('click', () => {
                const link = document.querySelector(`.dropdown a[data-target="${button.dataset.shippingView}"]`);
                if (link) link.click();
            });
        });
    };

    /**
     * Wire the KPI cards on any shipping page.
     *
     * This lived inside renderRoutes, so only the route page's cards responded.
     * On the fleet landing page -- the first shipping screen anyone sees -- all
     * four boxes were inert: no handler, no pointer cursor, no indication they
     * were meant to do anything.
     *
     * `targets` maps a card's key to the section it explains.
     */
    const bindKpiCards = (root, targets) => {
        root.querySelectorAll('[data-shipping-kpi]').forEach((card) => {
            const run = () => {
                root.querySelectorAll('.shipping-kpi.is-active')
                    .forEach((n) => n.classList.remove('is-active'));
                card.classList.add('is-active');
                const t = targets[card.dataset.shippingKpi];
                if (!t) return;
                const el = root.querySelector(t.section);
                if (el) {
                    // scrollIntoView walks up to the nearest scrollable ancestor
                    // and, with this absolutely-positioned surface, resolved to
                    // the document instead of the panel -- so nothing moved.
                    // Offsetting the container directly is unambiguous.
                    const top = el.getBoundingClientRect().top
                        - root.getBoundingClientRect().top
                        + root.scrollTop - 12;
                    root.scrollTo({ top: Math.max(0, top), behavior: 'smooth' });
                }
                if (t.flash) {
                    const row = root.querySelector(t.flash);
                    if (row) {
                        row.style.background = 'rgba(56,189,248,0.12)';
                        setTimeout(() => { row.style.background = ''; }, 1400);
                    }
                }
            };
            card.addEventListener('click', run);
            card.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); run(); }
            });
        });
    };

    const renderFleet = (data, root) => {
        const rows = [...data.fleet.fleet_by_type].sort((a, b) => b.dwt - a.dwt);
        const topTwoShare = rows
            .filter(row => row.ship_type === 'dry_bulk' || row.ship_type === 'tanker')
            .reduce((sum, row) => sum + row.share_pct, 0);
        const content = `
            <section class="shipping-kpi-grid">
                <article class="shipping-kpi featured is-clickable" data-shipping-kpi="fleet-total"
                         role="button" tabindex="0" title="선종별 상세표로 이동">
                    <span class="shipping-kpi-label">세계 총 선복량</span>
                    <strong>${formatDwt(data.fleet.world_total_dwt)}</strong>
                    <small>약 ${(data.fleet.world_total_dwt / 1e8).toFixed(1)}억 DWT</small>
                </article>
                <article class="shipping-kpi is-clickable" data-shipping-kpi="fleet-bulk"
                         role="button" tabindex="0" title="차트에서 벌크선 강조">
                    <span class="shipping-kpi-label">벌크선</span>
                    <strong>${formatDwt(rows.find(row => row.ship_type === 'dry_bulk')?.dwt)}</strong>
                    <small>세계 선대 42.5%</small>
                </article>
                <article class="shipping-kpi is-clickable" data-shipping-kpi="fleet-tanker"
                         role="button" tabindex="0" title="차트에서 유조선 강조">
                    <span class="shipping-kpi-label">유조선</span>
                    <strong>${formatDwt(rows.find(row => row.ship_type === 'tanker')?.dwt)}</strong>
                    <small>세계 선대 27.5%</small>
                </article>
                <article class="shipping-kpi is-clickable" data-shipping-kpi="fleet-mix"
                         role="button" tabindex="0" title="선복량 차트로 이동">
                    <span class="shipping-kpi-label">벌크선 + 유조선</span>
                    <strong>${formatPct(topTwoShare, 0)}</strong>
                    <small>세계 DWT의 핵심 구성</small>
                </article>
            </section>
            <section class="shipping-grid two-columns" id="shipping-section-fleet-chart">
                <article class="shipping-panel shipping-chart-panel">
                    <div class="shipping-panel-heading">
                        <div><p class="shipping-panel-kicker">FLEET MIX</p><h2>선종별 세계 선복량</h2></div>
                        <span class="shipping-badge observed">UNCTAD 관측</span>
                    </div>
                    <div class="shipping-chart-wrap"><canvas id="shipping-fleet-chart"></canvas></div>
                </article>
                <article class="shipping-panel">
                    <div class="shipping-panel-heading">
                        <div><p class="shipping-panel-kicker">DATA DEFINITION</p><h2>숫자를 읽는 법</h2></div>
                    </div>
                    <div class="shipping-definition-list">
                        <div><span>기준일</span><strong>${escapeHtml(data.fleet.as_of)}</strong></div>
                        <div><span>측정 단위</span><strong>DWT · 재화중량톤</strong></div>
                        <div><span>대상 선박</span><strong>100 GT 이상 추진 상선</strong></div>
                        <div><span>항로 데이터와 차이</span><strong>선대는 관측, 항로는 모델 추정</strong></div>
                    </div>
                    <p class="shipping-note">${escapeHtml(data.fleet.rounding_note)}</p>
                </article>
            </section>
            <section class="shipping-panel" id="shipping-section-fleet-table">
                <div class="shipping-panel-heading">
                    <div><p class="shipping-panel-kicker">WORLD FLEET TABLE</p><h2>선종별 상세</h2></div>
                </div>
                <div class="shipping-table-wrap">
                    <table class="shipping-table">
                        <thead><tr><th>선종</th><th>선복량</th><th>세계 비중</th><th>데이터 성격</th></tr></thead>
                        <tbody>${rows.map(row => `
                            <tr data-ship-type="${escapeHtml(row.ship_type)}">
                                <td><span class="shipping-color-dot" style="background:${SHIP_TYPE_COLORS[row.ship_type]}"></span>${SHIP_TYPE_LABELS[row.ship_type] || row.ship_type}</td>
                                <td>${formatDwt(row.dwt)}</td>
                                <td>${formatPct(row.share_pct)}</td>
                                <td><span class="shipping-badge observed">연간 관측</span></td>
                            </tr>
                        `).join('')}</tbody>
                    </table>
                </div>
            </section>
        `;
        root.innerHTML = shell(data, 'shipping_fleet', content);
        bindInternalNavigation(root);
        bindKpiCards(root, {
            'fleet-total':  { section: '#shipping-section-fleet-table' },
            'fleet-bulk':   { section: '#shipping-section-fleet-chart',
                              flash: 'tr[data-ship-type="dry_bulk"]' },
            'fleet-tanker': { section: '#shipping-section-fleet-chart',
                              flash: 'tr[data-ship-type="tanker"]' },
            'fleet-mix':    { section: '#shipping-section-fleet-chart' },
        });
        createChart(root, 'shipping-fleet-chart', {
            type: 'bar',
            data: {
                labels: rows.map(row => SHIP_TYPE_LABELS[row.ship_type] || row.ship_type),
                datasets: [{
                    label: '세계 선복량 (백만 DWT)',
                    data: rows.map(row => row.dwt / 1e6),
                    backgroundColor: rows.map(row => SHIP_TYPE_COLORS[row.ship_type]),
                    borderRadius: 6,
                    borderSkipped: false
                }]
            },
            options: chartOptions({ horizontal: true, unit: 'M DWT' })
        });
    };

    const routeStatusBadge = route => route.input_status?.startsWith('scenario_seed')
        ? '<span class="shipping-badge estimated">초기 추정값</span>'
        : '<span class="shipping-badge observed">관측 입력</span>';

    const catalogStatusBadge = status => status === 'capacity_model_active'
        ? '<span class="shipping-badge estimated">용량 모델 연결</span>'
        : '<span class="shipping-badge neutral">공공 화물량 대기</span>';

    const renderRoutes = (data, root, selectedId) => {
        const routes = [...data.routes].sort((a, b) => b.baseline.baseline_required_dwt - a.baseline.baseline_required_dwt);
        const catalog = data.route_catalog || [];
        const selected = routes.find(route => route.id === selectedId) || routes[0];
        const interval = selected.baseline.interval?.baseline_required_dwt || {};
        const selectedDirections = selected.directions || [];
        const capacityDriver = selectedDirections.find(direction => direction.id === selected.baseline.capacity_driver_direction_id);
        const activeCatalogCount = catalog.filter(route => route.model_status === 'capacity_model_active').length;
        const directionMarkup = selectedDirections.length ? `
            <div class="shipping-definition-list direction-flows">
                ${selectedDirections.map(direction => `
                    <div>
                        <span>${escapeHtml(direction.name_ko)}</span>
                        <strong>${direction.annual_cargo_tonnes == null ? '공공데이터 연결 대기' : formatTonnes(direction.annual_cargo_tonnes)}</strong>
                    </div>
                `).join('')}
            </div>
            <p class="shipping-note">양방향 정기선은 두 방향을 합산하지 않고, 화물량÷적재율이 더 큰 방향이 배치 선복량을 결정합니다.${capacityDriver ? ` 현재 기준 방향은 ${escapeHtml(capacityDriver.name_ko)}입니다.` : ''}</p>
        ` : '';
        const content = `
            <div class="shipping-callout warning">
                <strong>대형선 중심 v1.1:</strong> ${catalog.length || routes.length}개 세부 항로를 정의했고 ${activeCatalogCount || routes.length}개에 용량 계산이 연결되어 있습니다. 신규 항로는 공공 화물량이 들어오기 전까지 계산값을 만들지 않습니다.
            </div>
            <section class="shipping-control-bar">
                <label for="shipping-route-select">분석 항로</label>
                <select id="shipping-route-select" class="shipping-select">
                    ${routes.map(route => `<option value="${escapeHtml(route.id)}" ${route.id === selected.id ? 'selected' : ''}>[${SHIP_TYPE_LABELS[route.ship_type]} · ${escapeHtml(route.vessel_class_ko || '선형 미분류')}] ${escapeHtml(route.name_ko)}</option>`).join('')}
                </select>
                ${routeStatusBadge(selected)}
            </section>
            <section class="shipping-kpi-grid">
                <article class="shipping-kpi featured is-clickable" data-shipping-kpi="required" role="button" tabindex="0" title="모델 입력 패널로 이동">
                    <span class="shipping-kpi-label">필요 선복량</span>
                    <strong>${formatDwt(selected.baseline.baseline_required_dwt)}</strong>
                    <small>DWT-equivalent 추정 · 클릭 시 상세</small>
                </article>
                <article class="shipping-kpi is-clickable" data-shipping-kpi="range" role="button" tabindex="0" title="불확실성 구간 설명">
                    <span class="shipping-kpi-label">불확실성 P10–P90</span>
                    <strong>${formatDwt(interval.p10)} – ${formatDwt(interval.p90)}</strong>
                    <small>입력 범위 기반 · 클릭 시 산식</small>
                </article>
                <article class="shipping-kpi is-clickable" data-shipping-kpi="fleet-share" role="button" tabindex="0" title="전 항로 비교표">
                    <span class="shipping-kpi-label">해당 선종 선대 비중</span>
                    <strong>${formatPct(selected.baseline.route_share_of_type_fleet_pct, 2)}</strong>
                    <small>${SHIP_TYPE_LABELS[selected.ship_type]} · 클릭 시 비교</small>
                </article>
                <article class="shipping-kpi is-clickable" data-shipping-kpi="cycle" role="button" tabindex="0" title="왕복 주기 입력 확인">
                    <span class="shipping-kpi-label">왕복 운항주기</span>
                    <strong>${formatNumber(selected.baseline.baseline_cycle_days, 1)}일</strong>
                    <small>${escapeHtml(selected.origin)} → ${escapeHtml(selected.destination)}</small>
                </article>
            </section>
            <section class="shipping-grid two-columns wide-first" id="shipping-section-model">
                <article class="shipping-panel shipping-chart-panel" id="shipping-section-chart">
                    <div class="shipping-panel-heading"><div><p class="shipping-panel-kicker">ROUTE COMPARISON</p><h2>대표 항로 필요 선복량</h2></div><span>백만 DWT</span></div>
                    <div class="shipping-chart-wrap tall"><canvas id="shipping-routes-chart"></canvas></div>
                </article>
                <article class="shipping-panel" id="shipping-section-inputs">
                    <div class="shipping-panel-heading"><div><p class="shipping-panel-kicker">MODEL INPUTS</p><h2>${escapeHtml(selected.name_ko)}</h2></div></div>
                    <div class="shipping-definition-list">
                        <div><span>기준 선형</span><strong>${escapeHtml(selected.vessel_class_ko || '미분류')}</strong></div>
                        <div><span>기준 크기</span><strong>${formatReferenceSize(selected.reference_size)}</strong></div>
                        <div><span>벤치마크 계열</span><strong>${escapeHtml(selected.benchmark_family || '광역 화물 회랑')}</strong></div>
                        <div><span>연간 화물톤</span><strong>${formatTonnes(selected.annual_cargo_tonnes)}</strong></div>
                        <div><span>편도 거리</span><strong>${formatNumber(selected.model_inputs?.distance_nm_one_way)} NM</strong></div>
                        <div><span>평균 선속</span><strong>${formatNumber(selected.model_inputs?.speed_knots, 1)} knots</strong></div>
                        <div><span>유효 적재율</span><strong>${formatPct((selected.model_inputs?.utilization || 0) * 100)}</strong></div>
                        <div><span>예비 선복량</span><strong>${formatPct((selected.model_inputs?.reserve_margin || 0) * 100)}</strong></div>
                        <div id="shipping-kpi-cycle-row"><span>왕복 운항주기</span><strong>${formatNumber(selected.baseline.baseline_cycle_days, 1)}일</strong></div>
                        <div id="shipping-kpi-range-row"><span>필요 선복 P10–P90</span><strong>${formatDwt(interval.p10)} – ${formatDwt(interval.p90)}</strong></div>
                    </div>
                    ${directionMarkup}
                    <p class="shipping-formula">${selectedDirections.length
                        ? '필요 DWT = max(방향별 연간 화물톤 ÷ 적재율) × 왕복주기 ÷ 365'
                        : '필요 DWT = 연간 화물톤 × 왕복주기 ÷ (365 × 적재율)'}</p>
                </article>
            </section>
            <section class="shipping-panel" id="shipping-section-table">
                <div class="shipping-panel-heading"><div><p class="shipping-panel-kicker">ALL ROUTES</p><h2>항로별 비교표</h2></div></div>
                <div class="shipping-table-wrap">
                    <table class="shipping-table">
                        <thead><tr><th>항로</th><th>선종·선형</th><th>필요 선복량</th><th>선종 선대 비중</th><th>왕복주기</th><th>상태</th></tr></thead>
                        <tbody>${routes.map(route => `
                            <tr class="${route.id === selected.id ? 'selected-row' : ''}" data-route-id="${escapeHtml(route.id)}" role="button" tabindex="0">
                                <td>${escapeHtml(route.name_ko)}</td>
                                <td>${SHIP_TYPE_LABELS[route.ship_type] || route.ship_type}<br><small>${escapeHtml(route.vessel_class_ko || '미분류')}</small></td>
                                <td>${formatDwt(route.baseline.baseline_required_dwt)}</td>
                                <td>${formatPct(route.baseline.route_share_of_type_fleet_pct, 2)}</td>
                                <td>${formatNumber(route.baseline.baseline_cycle_days, 1)}일</td>
                                <td>${routeStatusBadge(route)}</td>
                            </tr>
                        `).join('')}</tbody>
                    </table>
                </div>
            </section>
            ${catalog.length ? `
                <section class="shipping-panel">
                    <div class="shipping-panel-heading"><div><p class="shipping-panel-kicker">LARGE-VESSEL ROUTE CATALOG</p><h2>대형선 중심 세부 항로 ${catalog.length}개</h2></div><span>${activeCatalogCount}개 계산 연결</span></div>
                    <div class="shipping-table-wrap">
                        <table class="shipping-table">
                            <thead><tr><th>선종</th><th>항로·서비스</th><th>기준 선형</th><th>벤치마크</th><th>상태</th></tr></thead>
                            <tbody>${catalog.map(route => `
                                <tr>
                                    <td>${SHIP_TYPE_LABELS[route.ship_type] || route.ship_type}</td>
                                    <td>${escapeHtml(route.name_ko)}</td>
                                    <td>${escapeHtml(route.vessel_class_ko)}</td>
                                    <td>${escapeHtml(route.benchmark_code)}</td>
                                    <td>${catalogStatusBadge(route.model_status)}</td>
                                </tr>
                            `).join('')}</tbody>
                        </table>
                    </div>
                </section>
            ` : ''}
        `;
        root.innerHTML = shell(data, 'shipping_routes', content);
        bindInternalNavigation(root);
        root.querySelector('#shipping-route-select')?.addEventListener('change', event => {
            destroyCharts();
            renderRoutes(data, root, event.target.value);
        });

        const scrollToSection = (id, highlightRowId) => {
            const el = root.querySelector(id);
            if (!el) return;
            el.scrollIntoView({ behavior: 'smooth', block: 'start' });
            el.classList.add('is-active');
            setTimeout(() => el.classList.remove('is-active'), 1200);
            if (highlightRowId) {
                const row = root.querySelector(`[data-route-id="${highlightRowId}"]`);
                row?.classList.add('selected-row');
            }
        };
        const onKpi = (kpi) => {
            root.querySelectorAll('.shipping-kpi.is-active').forEach(n => n.classList.remove('is-active'));
            root.querySelector(`[data-shipping-kpi="${kpi}"]`)?.classList.add('is-active');
            if (kpi === 'required' || kpi === 'cycle' || kpi === 'range') {
                scrollToSection('#shipping-section-inputs');
                const flashId = kpi === 'cycle' ? '#shipping-kpi-cycle-row'
                    : kpi === 'range' ? '#shipping-kpi-range-row' : null;
                if (flashId) {
                    const row = root.querySelector(flashId);
                    if (row) {
                        row.style.background = 'rgba(56,189,248,0.12)';
                        setTimeout(() => { row.style.background = ''; }, 1400);
                    }
                }
            } else if (kpi === 'fleet-share') {
                scrollToSection('#shipping-section-table');
                scrollToSection('#shipping-section-chart');
            }
        };
        root.querySelectorAll('[data-shipping-kpi]').forEach(card => {
            const run = () => onKpi(card.dataset.shippingKpi);
            card.addEventListener('click', run);
            card.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    run();
                }
            });
        });
        root.querySelectorAll('tr[data-route-id]').forEach(row => {
            row.style.cursor = 'pointer';
            const pick = () => {
                destroyCharts();
                renderRoutes(data, root, row.dataset.routeId);
            };
            row.addEventListener('click', pick);
            row.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    pick();
                }
            });
        });

        createChart(root, 'shipping-routes-chart', {
            type: 'bar',
            data: {
                labels: routes.map(route => route.name_ko.replace(' → ', '→')),
                datasets: [{
                    label: '필요 선복량 (백만 DWT)',
                    data: routes.map(route => route.baseline.baseline_required_dwt / 1e6),
                    backgroundColor: routes.map(route => route.id === selected.id ? '#38bdf8' : 'rgba(129, 140, 248, 0.55)'),
                    borderRadius: 5,
                    borderSkipped: false
                }]
            },
            options: chartOptions({ unit: 'M DWT', rotateLabels: true })
        });
    };

    const statusForChange = change => {
        if (change <= -25) return { label: '위험', cls: 'danger' };
        if (change <= -10) return { label: '주의', cls: 'warning' };
        return { label: '정상 범위', cls: 'ok' };
    };

    const renderChokepoints = (data, root) => {
        const points = data.chokepoints.map(point => ({ ...point, live: data.chokepoints_live?.[point.id] }));
        const cards = points.map(point => {
            const metric = point.live?.metrics?.all;
            const change = metric?.change_pct ?? null;
            const status = change === null ? { label: '데이터 없음', cls: 'neutral' } : statusForChange(change);
            return `
                <article class="shipping-chokepoint-card">
                    <div class="shipping-chokepoint-head">
                        <div><span>${escapeHtml(point.name_en)}</span><h3>${escapeHtml(point.name_ko)}</h3></div>
                        <span class="shipping-status ${status.cls}">${status.label}</span>
                    </div>
                    <strong class="shipping-change ${change < 0 ? 'negative' : 'positive'}">${change === null ? '—' : formatPct(change)}</strong>
                    <p>전체 통항 capacity · 최근 7일 vs 직전 28일</p>
                    <div class="shipping-mini-metrics">
                        <span>컨테이너 <b>${point.live?.metrics?.container ? formatPct(point.live.metrics.container.change_pct) : '—'}</b></span>
                        <span>벌크 <b>${point.live?.metrics?.dry_bulk ? formatPct(point.live.metrics.dry_bulk.change_pct) : '—'}</b></span>
                        <span>탱커 <b>${point.live?.metrics?.tanker ? formatPct(point.live.metrics.tanker.change_pct) : '—'}</b></span>
                    </div>
                    <small>최근 관측 ${formatDate(point.live?.latest_date)}</small>
                </article>
            `;
        }).join('');
        const content = `
            <div class="shipping-callout info">
                <strong>해석 주의:</strong> 아래 수치는 단기 통항 capacity 이상치이며 물리적 봉쇄율을 뜻하지 않습니다. 0보다 낮을수록 직전 28일보다 통항 선복량이 감소했다는 의미입니다.
            </div>
            <section class="shipping-chokepoint-grid">${cards}</section>
            <section class="shipping-grid two-columns wide-first">
                <article class="shipping-panel shipping-chart-panel">
                    <div class="shipping-panel-heading"><div><p class="shipping-panel-kicker">LIVE CAPACITY SIGNAL</p><h2>초크포인트별 통항 capacity 변화</h2></div><span class="shipping-badge observed">IMF PortWatch</span></div>
                    <div class="shipping-chart-wrap tall"><canvas id="shipping-chokepoint-chart"></canvas></div>
                </article>
                <article class="shipping-panel">
                    <div class="shipping-panel-heading"><div><p class="shipping-panel-kicker">SIGNAL METHOD</p><h2>모니터 산식</h2></div></div>
                    <div class="shipping-formula-block">
                        <span>Capacity ratio</span>
                        <strong>최근 7일 평균 ÷ 직전 28일 평균</strong>
                    </div>
                    <div class="shipping-definition-list compact">
                        <div><span>−10% 이내</span><strong class="positive-text">정상 범위</strong></div>
                        <div><span>−10% ~ −25%</span><strong class="warning-text">주의</strong></div>
                        <div><span>−25% 이하</span><strong class="negative-text">위험</strong></div>
                    </div>
                    <p class="shipping-note">요일·계절성과 선종 구성이 변할 수 있으므로 실제 봉쇄 판단에는 사건 정보와 장기 기준선을 함께 확인해야 합니다.</p>
                </article>
            </section>
        `;
        root.innerHTML = shell(data, 'shipping_chokepoints', content);
        bindInternalNavigation(root);
        createChart(root, 'shipping-chokepoint-chart', {
            type: 'bar',
            data: {
                labels: points.map(point => point.name_ko),
                datasets: [{
                    label: '전체 capacity 변화 (%)',
                    data: points.map(point => point.live?.metrics?.all?.change_pct ?? 0),
                    backgroundColor: points.map(point => {
                        const value = point.live?.metrics?.all?.change_pct ?? 0;
                        return value <= -25 ? '#ef4444' : value <= -10 ? '#f59e0b' : '#22c55e';
                    }),
                    borderRadius: 5,
                    borderSkipped: false
                }]
            },
            options: chartOptions({ unit: '%', zeroLine: true })
        });
    };

    const simulateRoute = (route, scenario) => {
        const exposure = route.chokepoints?.find(item => item.id === scenario.chokepoint_id);
        if (!exposure) return null;
        const input = route.model_inputs || {};
        const horizonDays = 28;
        const durationFactor = Math.min(scenario.duration_days / horizonDays, 1);
        const affected = (exposure.exposure_share || 1) * scenario.closure_fraction * durationFactor;
        const rerouted = affected * (exposure.response?.reroute || 0);
        const waiting = affected * (exposure.response?.wait || 0);
        const cancelled = affected * (exposure.response?.cancel || 0);
        const extraCycleDays = 2 * (exposure.reroute_extra_nm_one_way || 0) / (input.speed_knots || 1) / 24;
        const annualCargo = route.annual_cargo_tonnes || 0;
        const utilization = input.utilization || 1;
        const baseline = route.baseline.baseline_required_dwt || 0;
        const allocated = baseline * (1 + (input.reserve_margin || 0));
        const retainedBase = baseline * (1 - cancelled);
        const delayCapacity = annualCargo / (365 * utilization)
            * (rerouted * extraCycleDays + waiting * scenario.waiting_days);
        const disrupted = retainedBase + delayCapacity;
        const capacityGap = Math.max(0, disrupted - allocated);
        const coverage = disrupted > 0 ? Math.min(1, allocated / disrupted) : 1;
        const deliverable = (1 - cancelled) * coverage;
        return {
            route,
            affected,
            rerouted,
            waiting,
            cancelled,
            baseline,
            disrupted,
            absorbed: Math.max(0, delayCapacity),
            capacityGap,
            deliverable,
            trafficChangePct: (deliverable - 1) * 100,
            lostCargo: annualCargo / 365 * horizonDays * cancelled
        };
    };

    const scenarioResultMarkup = (results, scenario) => {
        if (!results.length) {
            return '<div class="shipping-empty">이 초크포인트에 연결된 대표 항로가 없습니다.</div>';
        }
        const baselineTotal = results.reduce((sum, row) => sum + row.baseline, 0);
        const absorbed = results.reduce((sum, row) => sum + row.absorbed, 0);
        const gap = results.reduce((sum, row) => sum + row.capacityGap, 0);
        const lost = results.reduce((sum, row) => sum + row.lostCargo, 0);
        const deliverable = results.reduce((sum, row) => sum + row.deliverable * row.baseline, 0) / baselineTotal;
        return `
            <section class="shipping-kpi-grid scenario-kpis">
                <article class="shipping-kpi featured"><span class="shipping-kpi-label">추가로 묶이는 선복량</span><strong>${formatDwt(absorbed)}</strong><small>우회 + 대기 총흡수</small></article>
                <article class="shipping-kpi"><span class="shipping-kpi-label">예비분 초과 부족</span><strong>${formatDwt(gap)}</strong><small>capacity gap</small></article>
                <article class="shipping-kpi"><span class="shipping-kpi-label">28일 손실 화물</span><strong>${formatTonnes(lost)}</strong><small>취소 가정 반영</small></article>
                <article class="shipping-kpi"><span class="shipping-kpi-label">배송가능 트래픽 변화</span><strong class="negative-text">${formatPct((deliverable - 1) * 100)}</strong><small>${formatNumber(scenario.duration_days)}일 충격</small></article>
            </section>
            <section class="shipping-grid two-columns wide-first">
                <article class="shipping-panel shipping-chart-panel">
                    <div class="shipping-panel-heading"><div><p class="shipping-panel-kicker">CAPACITY BEFORE / AFTER</p><h2>영향 항로 선복량 변화</h2></div><span>백만 DWT</span></div>
                    <div class="shipping-chart-wrap tall"><canvas id="shipping-scenario-chart"></canvas></div>
                </article>
                <article class="shipping-panel">
                    <div class="shipping-panel-heading"><div><p class="shipping-panel-kicker">AFFECTED ROUTES</p><h2>항로별 충격</h2></div></div>
                    <div class="shipping-table-wrap">
                        <table class="shipping-table compact-table">
                            <thead><tr><th>항로</th><th>흡수 DWT</th><th>트래픽</th></tr></thead>
                            <tbody>${results.map(row => `
                                <tr><td>${escapeHtml(row.route.name_ko)}</td><td>${formatDwt(row.absorbed)}</td><td class="negative-text">${formatPct(row.trafficChangePct)}</td></tr>
                            `).join('')}</tbody>
                        </table>
                    </div>
                </article>
            </section>
        `;
    };

    const renderScenarios = (data, root) => {
        const scenarios = data.scenarios?.length ? data.scenarios : data.scenario_summary;
        const initial = scenarios.find(item => item.id === 'suez_100pct_28d') || scenarios[0];
        const content = `
            <div class="shipping-callout warning"><strong>시나리오 모델:</strong> 봉쇄 가능성을 예측하는 것이 아니라, 입력한 봉쇄가 발생했을 때 필요한 선복량과 배송가능 트래픽을 계산합니다.</div>
            <section class="shipping-simulator-controls">
                <label>기준 시나리오
                    <select id="shipping-scenario-preset" class="shipping-select">
                        ${scenarios.map(item => `<option value="${escapeHtml(item.id)}" ${item.id === initial.id ? 'selected' : ''}>${escapeHtml(item.name_ko || item.id)}</option>`).join('')}
                    </select>
                </label>
                <label>봉쇄율 <output id="shipping-closure-output" aria-live="polite">${Math.round(initial.closure_fraction * 100)}%</output>
                    <input id="shipping-closure-range" aria-label="봉쇄율" type="range" min="0" max="100" step="5" value="${Math.round(initial.closure_fraction * 100)}">
                </label>
                <label>지속기간 <output id="shipping-duration-output" aria-live="polite">${initial.duration_days}일</output>
                    <input id="shipping-duration-range" aria-label="지속기간" type="range" min="1" max="28" step="1" value="${Math.min(initial.duration_days, 28)}">
                </label>
                <label>평균 대기 <output id="shipping-wait-output" aria-live="polite">${initial.waiting_days || 7}일</output>
                    <input id="shipping-wait-range" aria-label="평균 대기" type="range" min="0" max="28" step="1" value="${initial.waiting_days || 7}">
                </label>
            </section>
            <div id="shipping-scenario-results"></div>
            <p class="shipping-note footer-note">우회·대기·취소 비율은 항로 설정값을 사용합니다. ‘추가로 묶이는 선복량’은 gross absorption, ‘예비분 초과 부족’은 실제 capacity gap입니다.</p>
        `;
        root.innerHTML = shell(data, 'shipping_scenarios', content);
        bindInternalNavigation(root);

        const presetEl = root.querySelector('#shipping-scenario-preset');
        const closureEl = root.querySelector('#shipping-closure-range');
        const durationEl = root.querySelector('#shipping-duration-range');
        const waitEl = root.querySelector('#shipping-wait-range');
        const resultsEl = root.querySelector('#shipping-scenario-results');

        const update = () => {
            const preset = scenarios.find(item => item.id === presetEl.value) || scenarios[0];
            const scenario = {
                chokepoint_id: preset.chokepoint_id,
                closure_fraction: Number(closureEl.value) / 100,
                duration_days: Number(durationEl.value),
                waiting_days: Number(waitEl.value)
            };
            const setOutputValue = (selector, label, value) => {
                const output = root.querySelector(selector);
                output.value = value;
                output.textContent = value;
                output.setAttribute('aria-label', `${label}: ${value}`);
            };
            setOutputValue('#shipping-closure-output', '봉쇄율', `${closureEl.value}%`);
            setOutputValue('#shipping-duration-output', '지속기간', `${durationEl.value}일`);
            setOutputValue('#shipping-wait-output', '평균 대기', `${waitEl.value}일`);
            const results = data.routes.map(route => simulateRoute(route, scenario)).filter(Boolean)
                .sort((a, b) => b.absorbed - a.absorbed);
            resultsEl.innerHTML = scenarioResultMarkup(results, scenario);
            createChart(root, 'shipping-scenario-chart', {
                type: 'bar',
                data: {
                    labels: results.map(row => row.route.name_ko),
                    datasets: [
                        { label: '정상 필요 DWT', data: results.map(row => row.baseline / 1e6), backgroundColor: 'rgba(100, 116, 139, 0.7)', borderRadius: 4 },
                        { label: '충격 후 필요 DWT', data: results.map(row => row.disrupted / 1e6), backgroundColor: '#38bdf8', borderRadius: 4 }
                    ]
                },
                options: chartOptions({ unit: 'M DWT', rotateLabels: true })
            });
        };

        presetEl.addEventListener('change', () => {
            const preset = scenarios.find(item => item.id === presetEl.value) || scenarios[0];
            closureEl.value = Math.round(preset.closure_fraction * 100);
            durationEl.value = Math.min(preset.duration_days, 28);
            waitEl.value = preset.waiting_days || 7;
            update();
        });
        [closureEl, durationEl, waitEl].forEach(input => input.addEventListener('input', update));
        update();
    };

    const renderEnvironment = (data, root) => {
        const env = data.environment || {};
        const scenarios = env.scenarios || [];

        const content = `
            ${env.methodology_ko ? `<div class="shipping-callout info">${escapeHtml(env.methodology_ko)}</div>` : ''}
            <section class="shipping-panel" id="shipping-section-environment-table">
                <div class="shipping-panel-heading">
                    <div><p class="shipping-panel-kicker">SCENARIO OUTLOOK</p><h2>규제 대응 시나리오별 유효 선복량</h2></div>
                </div>
                ${scenarios.length ? `
                <div class="shipping-table-wrap">
                    <table class="shipping-table">
                        <thead>
                            <tr>
                                <th>시나리오</th>
                                <th>CII 감축 (2019 대비)</th>
                                <th>유효 선복량 손실</th>
                                <th>용량 유지율 (저·중·고)</th>
                                <th>대상 항로</th>
                            </tr>
                        </thead>
                        <tbody>${scenarios.map(sc => {
                            const range = sc.effective_capacity_retention_rate_range || {};
                            return `
                            <tr>
                                <td>
                                    ${escapeHtml(sc.name_ko || sc.id)}
                                    <br><small>${sc.year || ''} · ${sc.status === 'scenario_provisional' ? '잠정' : escapeHtml(sc.status || '')}</small>
                                </td>
                                <td>${sc.cii_reduction_vs_2019_pct != null ? `${sc.cii_reduction_vs_2019_pct}%` : '—'}</td>
                                <td>${formatDwt(sc.effective_dwt_loss)}</td>
                                <td>${formatPct((range.low || 0) * 100)} · <strong>${formatPct((range.central || 0) * 100)}</strong> · ${formatPct((range.high || 0) * 100)}</td>
                                <td>${sc.representative_route_count != null ? `${sc.representative_route_count}개` : '—'}</td>
                            </tr>`;
                        }).join('')}</tbody>
                    </table>
                </div>` : '<p class="shipping-empty">시나리오 데이터 없음</p>'}
            </section>
            ${Array.isArray(env.warnings_ko) && env.warnings_ko.length ? `
            <div class="shipping-callout warning">
                <strong>해석 시 주의:</strong>
                <ul>${env.warnings_ko.map(w => `<li>${escapeHtml(w)}</li>`).join('')}</ul>
            </div>` : ''}
            ${Array.isArray(env.sources) && env.sources.length ? `
            <p class="shipping-note">출처: ${env.sources.map(s => `<a class="shipping-source-link" href="${escapeHtml(s.url)}" target="_blank" rel="noopener">${escapeHtml(s.name)}</a>`).join(' · ')}</p>` : ''}
        `;
        root.innerHTML = shell(data, 'shipping_environment', content);
        bindInternalNavigation(root);
    };

    const chartOptions = ({ horizontal = false, unit = '', rotateLabels = false, zeroLine = false } = {}) => ({
        responsive: true,
        maintainAspectRatio: false,
        indexAxis: horizontal ? 'y' : 'x',
        animation: { duration: 350 },
        plugins: {
            legend: { labels: { color: '#cbd5e1', boxWidth: 12, usePointStyle: true } },
            tooltip: {
                backgroundColor: 'rgba(15, 23, 42, 0.96)',
                borderColor: 'rgba(148, 163, 184, 0.25)',
                borderWidth: 1,
                callbacks: { label: context => `${context.dataset.label}: ${formatNumber(context.parsed[horizontal ? 'x' : 'y'], 1)} ${unit}` }
            }
        },
        scales: {
            x: {
                grid: { color: zeroLine ? 'rgba(148, 163, 184, 0.12)' : 'rgba(148, 163, 184, 0.06)' },
                ticks: { color: '#94a3b8', maxRotation: rotateLabels ? 35 : 0, minRotation: 0 }
            },
            y: {
                grid: { color: 'rgba(148, 163, 184, 0.08)' },
                ticks: { color: '#94a3b8' }
            }
        }
    });

    const render = async (target, root) => {
        destroyCharts();
        root.scrollTop = 0;
        root.classList.add('shipping-surface');
        root.dataset.shippingTarget = target;
        root.innerHTML = '<div class="shipping-loading"><span></span><p>선복량 데이터를 불러오는 중입니다.</p></div>';
        try {
            const data = await loadData();
            if (root.dataset.shippingTarget !== target) return;
            if (target === 'shipping_fleet') renderFleet(data, root);
            else if (target === 'shipping_routes') renderRoutes(data, root);
            else if (target === 'shipping_chokepoints') renderChokepoints(data, root);
            else if (target === 'shipping_environment') renderEnvironment(data, root);
            else renderScenarios(data, root);
        } catch (error) {
            root.innerHTML = `
                <div class="shipping-error">
                    <strong>선복량 데이터를 표시하지 못했습니다.</strong>
                    <p>${escapeHtml(error.message)}</p>
                    <button type="button" id="shipping-retry">다시 시도</button>
                </div>`;
            root.querySelector('#shipping-retry')?.addEventListener('click', () => render(target, root));
        }
    };

    const unmount = root => {
        destroyCharts();
        root.classList.remove('shipping-surface');
        delete root.dataset.shippingTarget;
    };

    window.ShippingDashboard = { render, unmount };
})();
