"""Extract oil-palm maturity structure from official BPS province tables.

The generic province panel stores total planted area and CPO production by
producer category.  Palm production, however, is generated by mature area
(TM), not total planted area.  This extractor preserves BPS's immature (TBM),
mature (TM), and damaged/old (TTM) areas so production can be modelled as
``mature area * mature-area productivity``.
"""

import csv
import os
import re
import sys

from .build_db import CANONICAL, NUMBER, PROVINCES, pdf_pages
from .manifest import PUBLICATIONS


HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, "raw", "oil_palm")
OUT = os.path.join(HERE, "data", "palm_structure.csv")
HISTORY_OUT = os.path.join(HERE, "data", "palm_national_history.csv")

FIELDS = [
    "year", "province", "immature_ha", "mature_ha", "damaged_ha",
    "total_area_ha", "production_tonnes", "productivity_kg_ha",
    "data_status", "publication_id", "source_page", "source_table",
    "page_url",
]


def _structure_consistency(values):
    """Score a six-value row using both identities printed by BPS."""
    if len(values) != 6:
        return 1e12
    immature, mature, damaged, total, production, productivity = values
    if all(value is None for value in values):
        return 0.0
    if total is None:
        return 1e12
    area_sum = sum(value or 0 for value in [immature, mature, damaged])
    score = abs(area_sum - total) / max(1, total)
    if (production is not None and productivity is not None
            and mature is not None and mature > 0):
        implied = production * 1000 / mature
        score += abs(implied - productivity) / max(1, productivity)
    elif production is not None or productivity is not None:
        score += 1
    if productivity is not None and productivity > 10_000:
        score += 10
    return score


def _grouped_candidates(tokens, expected=6):
    candidates = []

    def visit(position, values):
        remaining_values = expected - len(values)
        remaining_tokens = len(tokens) - position
        if remaining_values == 0:
            if remaining_tokens == 0:
                candidates.append(values)
            return
        if remaining_tokens > remaining_values * 3:
            return
        if remaining_tokens <= (remaining_values - 1) * 3:
            visit(position, values + [None])
        if position >= len(tokens):
            return
        token = tokens[position]
        if token in {"-", "–", "—"}:
            visit(position + 1, values + [None])
            return
        for width in range(1, 4):
            group = tokens[position:position + width]
            if len(group) != width or any(not item.isdigit() for item in group):
                break
            if width > 1 and any(len(item) != 3 for item in group[1:]):
                break
            visit(position + width, values + [int("".join(group))])

    visit(0, [])
    return candidates


def structure_values(text):
    # Early books print productivity with decimal commas.  BPS rounds this to
    # whole kg/ha in recent books, so the decimals carry no modelling signal.
    text = re.sub(r",\d+(?=\s*$)", "", text.strip())
    tokens = NUMBER.findall(text)
    if "." in text and len(tokens) == 6:
        values = []
        for token in tokens:
            if token in {"-", "–", "—"}:
                values.append(None)
            else:
                values.append(int(token.lstrip(".").replace(".", "")))
        return values

    # Remove dots before repairing rows split by the diagonal bps.go.id
    # watermark (for example ``69p.892``).  The two printed identities choose
    # the only plausible grouping.
    raw_tokens = NUMBER.findall(text.replace(".", ""))
    candidates = _grouped_candidates(raw_tokens)
    if not candidates:
        return None
    return min(candidates, key=_structure_consistency)


def _history_consistency(values):
    if len(values) != 4 or values[3] is None:
        return 1e12
    return abs(sum(value or 0 for value in values[:3]) - values[3]) / max(
        1, values[3])


def history_values(text):
    tokens = NUMBER.findall(text)
    if "." in text and len(tokens) == 4:
        return [
            None if token in {"-", "–", "—"}
            else int(token.lstrip(".").replace(".", ""))
            for token in tokens
        ]
    candidates = _grouped_candidates(tokens, expected=4)
    if not candidates:
        return None
    return min(candidates, key=_history_consistency)


def _labeled_row(line):
    normalized = re.sub(r"\s+", " ", line).strip()
    # Printed total rows are uppercase.  Keeping this case-sensitive avoids
    # treating footer source text beginning with ``Indonesia, ...`` as a row.
    national = re.match(r"^INDONESIA\b", normalized)
    if national:
        return "INDONESIA", structure_values(normalized[national.end():])
    numbered = re.match(r"^\d+\s+(.+)$", normalized)
    if not numbered:
        return None
    rest = numbered.group(1)
    folded = rest.casefold()
    for province in sorted(PROVINCES, key=len, reverse=True):
        if folded.startswith(province.casefold() + " "):
            values = structure_values(rest[len(province):])
            return CANONICAL.get(province, province), values
    return None


def _table_year(page, allowed):
    normalized = re.sub(r"\s+", " ", page)
    patterns = [
        r"Condition of Crops.{0,180}?(20\d{2})(\*{0,2}|r)?",
        r"Keadaa+n Tanaman.{0,180}?(20\d{2})(\*{0,2}|r)?",
        r"Productivity of Crude Palm Oil by Province,?\s*(20\d{2})(\*{0,2}|r)?",
    ]
    for pattern in patterns:
        for year, marker in re.findall(pattern, normalized, re.IGNORECASE):
            if int(year) in allowed:
                return int(year), marker
    return None, ""


def parse_structure_page(page, publication, page_number):
    year, marker = _table_year(page, publication["data_years"])
    if year is None:
        return None
    header_end = re.search(r"(?m)^\s*1\s+", page)
    header = page[:header_end.start()] if header_end else page
    blocked = [
        "Smallholders", "Government Estates", "Private Estates",
        "Perkebunan Rakyat", "Perkebunan Besar Negara",
        "Perkebunan Besar Swasta",
    ]
    if any(label.casefold() in header.casefold() for label in blocked):
        return None

    parsed = []
    for line in page.splitlines():
        row = _labeled_row(line)
        if row is None or row[1] is None:
            continue
        if _structure_consistency(row[1]) <= 0.03:
            parsed.append(row)
    unique = {}
    for province, values in parsed:
        existing = unique.get(province)
        if existing is None or _structure_consistency(values) < _structure_consistency(existing):
            unique[province] = values
    # Early editions omit provinces without oil-palm estates and diagonal
    # watermarks can split a handful of otherwise valid rows across lines.
    # The national row plus a conservative producing-province floor prevents
    # a category-specific or contents page from being accepted.
    if "INDONESIA" not in unique or len(unique) < 10:
        return None

    table_match = re.search(
        r"(?:Tabel|Table)\s+(\d+\.\d+(?:\.\d+)?)\b",
        header,
        re.IGNORECASE,
    )
    if table_match is None:
        table_match = re.search(
            r"(?m)^\s*(\d+\.\d+(?:\.\d+)?)\s*$", header)
    table_id = table_match.group(1) if table_match else None
    status = "final"
    if marker == "*":
        status = "preliminary"
    elif marker == "**":
        status = "very_preliminary"
    elif marker.casefold() == "r":
        status = "revised"

    rows = []
    for province, values in unique.items():
        rows.append(dict(zip(FIELDS, [
            year, province, *values, status, publication["id"], page_number,
            table_id, publication["page_url"],
        ])))
    return rows


def extract(publications=PUBLICATIONS, raw_dir=RAW):
    selected = [item for item in publications if item["crop"] == "oil_palm"]
    by_year = {}
    failures = []
    for publication in selected:
        path = os.path.join(raw_dir, publication["id"] + ".pdf")
        if not os.path.exists(path):
            failures.append(publication["id"] + ": source PDF missing")
            continue
        found = set()
        # Raw text keeps watermark-crossed rows intact.  Unlike the generic
        # producer-category tables, these rows do not need fixed column
        # positions because TBM/TM/TTM/total/productivity provide two strong
        # consistency identities.
        for page_number, page in enumerate(pdf_pages(path, layout=False), start=1):
            rows = parse_structure_page(page, publication, page_number)
            if rows is None:
                continue
            year = rows[0]["year"]
            if year not in found:
                by_year[year] = rows
                found.add(year)
        expected = {year for year in publication["data_years"] if year >= 2005}
        for year in sorted(expected - found):
            failures.append("{}: structure table for {} not parsed".format(
                publication["id"], year))
    return [row for year in sorted(by_year) for row in by_year[year]], failures


def extract_national_history(publications=PUBLICATIONS, raw_dir=RAW):
    latest = max(
        (item for item in publications if item["crop"] == "oil_palm"),
        key=lambda item: item["publication_year"],
    )
    path = os.path.join(raw_dir, latest["id"] + ".pdf")
    if not os.path.exists(path):
        return [], [latest["id"] + ": source PDF missing"]
    area = {}
    production = {}
    source_pages = {}
    # Raw extraction keeps the four history values together; fixed-width
    # layout is better for province tables but is split by the diagonal BPS
    # watermark on several 2007--2016 history rows.
    for page_number, page in enumerate(pdf_pages(path, layout=False), start=1):
        normalized = re.sub(r"\s+", " ", page[:1600])
        if "Area of Oil Palm by Category of Producers" in normalized:
            target = area
            metric = "area"
        elif "Production of Crude Palm Oil by Category of Producers" in normalized:
            target = production
            metric = "production"
        else:
            continue
        for line in page.splitlines():
            match = re.match(r"^\s*(20\d{2})\s+(.+)$", line)
            if not match:
                continue
            values = history_values(match.group(2))
            if values is not None and _history_consistency(values) <= 0.001:
                target[int(match.group(1))] = values
                source_pages[metric] = page_number
    years = sorted(set(area) & set(production))
    rows = []
    for year in years:
        rows.append({
            "year": year,
            "government_area_ha": area[year][0],
            "private_area_ha": area[year][1],
            "smallholder_area_ha": area[year][2],
            "total_area_ha": area[year][3],
            "government_cpo_tonnes": production[year][0],
            "private_cpo_tonnes": production[year][1],
            "smallholder_cpo_tonnes": production[year][2],
            "total_cpo_tonnes": production[year][3],
            "publication_id": latest["id"],
            "area_source_page": source_pages.get("area"),
            "production_source_page": source_pages.get("production"),
            "page_url": latest["page_url"],
        })
    failures = [] if len(years) >= 20 else [
        "{}: expected at least 20 national history years, found {}".format(
            latest["id"], len(years))]
    return rows, failures


def main():
    rows, failures = extract()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    history, history_failures = extract_national_history()
    history_fields = [
        "year", "government_area_ha", "private_area_ha",
        "smallholder_area_ha", "total_area_ha", "government_cpo_tonnes",
        "private_cpo_tonnes", "smallholder_cpo_tonnes", "total_cpo_tonnes",
        "publication_id", "area_source_page", "production_source_page",
        "page_url",
    ]
    with open(HISTORY_OUT, "w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=history_fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(history)
    failures.extend(history_failures)
    years = sorted({row["year"] for row in rows})
    print("[palm:structure] wrote {} rows for {}-{} ({} seasons)".format(
        len(rows), min(years), max(years), len(years)))
    if history:
        print("[palm:structure] wrote {} national history rows for {}-{}".format(
            len(history), history[0]["year"], history[-1]["year"]))
    for failure in failures:
        print("[palm:structure] WARNING " + failure)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
