"""Research-grade, local-only Panama Canal hydrology and operations model.

The model deliberately separates three layers:

1. Hydrology: monthly Gatun level from precipitation and evaporation using the
   covariates and extreme-level weighting in Muñoz et al. (2025), *Drying of
   the Panama Canal in a Warming Climate*, Geophysical Research Letters,
   doi:10.1029/2025GL117038.
2. Operations: ACP-issued booking-slot and maximum-draft notices.  These are
   observed management decisions and override any statistical inference.
3. Traffic: official monthly ocean-going transit counts (when supplied) are
   modelled only after a chronological backtest beats a seasonal baseline.

Gatun level is never converted directly into DWT, ship counts, or a closure
percentage.  That relationship is mediated by ACP operations and is not a
physical constant.
"""

from __future__ import annotations

import csv
import calendar
import html
import io
import json
import math
import os
import re
import statistics
import tempfile
import urllib.request
from urllib.parse import quote, urljoin, urlsplit, urlunsplit
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass, replace
from datetime import date, datetime
from pathlib import Path
from typing import Any, Iterable


ACP_GATUN_DASHBOARD_PDF = "https://evtms-rpts.pancanal.com/eng/h2o/GatunWaterIndicators.pdf"
ACP_GATUN_PROJECTION_CSV = "https://evtms-rpts.pancanal.com/eng/h2o/Gatun_Water_Level_Projection.csv"
MUÑOZ_2025_DOI = "https://doi.org/10.1029/2025GL117038"
GPM_IMERG_DAILY_SHORT_NAME = "GPM_3IMERGDL"
GPM_IMERG_DAILY_VERSION = "07"
GPM_IMERG_COLLECTION_URL = "https://disc.gsfc.nasa.gov/datasets/GPM_3IMERGDL_07/summary"
# A documented rectangular monitoring window around the Gatun watershed.  It is
# deliberately not called a watershed polygon: the official basin boundary is
# not bundled with this local-only research module.
GATUN_MONITORING_BBOX = (8.6, -80.3, 9.7, -79.1)  # south, west, north, east
# The paper trains on nearly six decades of monthly observations.  Requiring
# fifteen years avoids pretending that a short weather record can support the
# paper's 20-basis-function smoother for each of four hydrological covariates.
MIN_HYDROLOGY_MONTHS = 180
MIN_TRANSIT_MONTHS = 36
ACP_ADVISORY_INDEX = "https://pancanal.com/en/maritime-services/advisory-to-shipping/"


class ACPModelError(ValueError):
    """Raised when an ACP input is absent or cannot be safely interpreted."""


@dataclass(frozen=True)
class GatunDashboardSnapshot:
    observation_date: str
    water_level_ft: float
    fresh_water_surcharge_pct: float | None
    neopanamax_max_draft_ft: float | None
    panamax_max_draft_ft: float | None
    projection_uploaded_at: str | None
    source_url: str


@dataclass(frozen=True)
class BookingSlotWindow:
    start_date: str
    end_date: str | None
    slots_per_day: int
    source_url: str
    advisory_id: str | None = None


@dataclass(frozen=True)
class MonthlyHydrologyRecord:
    month: str
    gatun_mean_ft: float
    precipitation_mm: float
    evaporation_mm: float
    oceangoing_transits_daily_average: float | None = None
    booking_slots_per_day: float | None = None
    neopanamax_max_draft_ft: float | None = None
    panamax_max_draft_ft: float | None = None
    oni_lag_6w: float | None = None


@dataclass(frozen=True)
class DailyGatunLevel:
    """An observed daily lake level, retained only in a user-local file."""

    observation_date: str
    water_level_ft: float


@dataclass(frozen=True)
class DailyMeteorology:
    """Daily weather values used only as a declared hydrology proxy."""

    observation_date: str
    precipitation_mm: float
    evaporation_proxy_mm: float


@dataclass(frozen=True)
class DailySatellitePrecipitation:
    """Area-weighted GPM IMERG daily precipitation in a declared monitor window.

    This is a recent-observation layer, not an interchangeable replacement for
    the long NASA POWER sensitivity series used by the hydrology backtest.
    """

    observation_date: str
    precipitation_mm: float
    product_id: str
    source_url: str


@dataclass(frozen=True)
class GatunProjectionPoint:
    """A published ACP estimate; not a prediction generated by this module."""

    projection_date: str
    water_level_ft: float
    fresh_water_surcharge_pct: float | None
    neopanamax_max_draft_ft: float | None
    panamax_max_draft_ft: float | None


@dataclass(frozen=True)
class MonthlyCanalOperations:
    """Official ACP monthly traffic/booking statistics parsed from an Advisory."""

    month: str
    arrivals_daily_average: float
    oceangoing_transits_daily_average: float
    oceangoing_transits_high: float
    oceangoing_transits_low: float
    canal_waters_time_hours: float
    in_transit_time_hours: float
    neopanamax_transits_daily_average: float | None
    booking_available_total: float | None
    booking_used_total: float | None
    booking_utilization_pct: float | None
    source_url: str
    advisory_id: str | None = None


@dataclass(frozen=True)
class MonthlyClimateForecastMember:
    """One member of a documented external precipitation/evaporation forecast."""

    source_id: str
    member_id: str
    month: str
    precipitation_mm: float
    evaporation_mm: float
    oni: float | None = None


def fetch_public_pdf(url: str, *, timeout_seconds: int = 45) -> bytes:
    """Download a public ACP document without persisting it in the repository."""

    parts = urlsplit(url)
    encoded_url = urlunsplit((parts.scheme, parts.netloc, quote(parts.path, safe="/%:@"), parts.query, parts.fragment))
    request = urllib.request.Request(
        encoded_url,
        headers={"User-Agent": "GlobalTradeDashboardResearch/1.0 (+noncommercial)"},
    )
    with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
        payload = response.read()
    if not payload.startswith(b"%PDF"):
        raise ACPModelError("ACP source did not return a PDF document")
    return payload


def fetch_public_text(url: str, *, timeout_seconds: int = 45) -> str:
    """Fetch a public text/CSV response in memory without a raw cache."""

    parts = urlsplit(url)
    encoded_url = urlunsplit((parts.scheme, parts.netloc, quote(parts.path, safe="/%:@"), parts.query, parts.fragment))
    request = urllib.request.Request(
        encoded_url,
        headers={"User-Agent": "GlobalTradeDashboardResearch/1.0 (+noncommercial)"},
    )
    with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
        return response.read().decode("utf-8-sig")


def _earthdata_token() -> str:
    """Get an Earthdata token from the process environment, never a source file."""

    token = os.environ.get("NASA_EARTHDATA") or os.environ.get("EARTHDATA_TOKEN")
    if not token:
        raise ACPModelError("NASA_EARTHDATA or EARTHDATA_TOKEN is required for GPM IMERG collection")
    return token


def _earthdata_request(url: str, token: str) -> urllib.request.Request:
    return urllib.request.Request(
        url,
        headers={
            "Authorization": f"Bearer {token}",
            "User-Agent": "GlobalTradeDashboardResearch/1.0 (+noncommercial)",
        },
    )


def _gpm_granules(start_date: str, end_date: str, token: str) -> list[tuple[str, str]]:
    """Resolve daily GPM IMERG files through CMR without storing an index cache."""

    try:
        start = datetime.strptime(start_date, "%Y-%m-%d").date()
        end = datetime.strptime(end_date, "%Y-%m-%d").date()
    except ValueError as exc:
        raise ACPModelError("GPM date range must use YYYY-MM-DD") from exc
    if end < start:
        raise ACPModelError("GPM end date precedes start date")
    if (end - start).days + 1 > 31:
        raise ACPModelError("GPM collection is capped at 31 days per local run to avoid bulk raw-data caching")
    query = urllib.parse.urlencode({
        "short_name": GPM_IMERG_DAILY_SHORT_NAME,
        "version": GPM_IMERG_DAILY_VERSION,
        "temporal": f"{start.isoformat()}T00:00:00Z,{end.isoformat()}T23:59:59Z",
        "page_size": "2000",
    })
    request = _earthdata_request(f"https://cmr.earthdata.nasa.gov/search/granules.json?{query}", token)
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            entries = json.loads(response.read().decode("utf-8"))["feed"]["entry"]
    except (KeyError, OSError, json.JSONDecodeError) as exc:
        raise ACPModelError("Earthdata CMR did not return GPM IMERG granules") from exc
    resolved = []
    for entry in entries:
        stamp = str(entry.get("time_start", ""))[:10]
        source_url = next(
            (str(link["href"]) for link in entry.get("links", []) if str(link.get("href", "")).endswith(".nc4")),
            None,
        )
        if source_url and re.fullmatch(r"\d{4}-\d{2}-\d{2}", stamp):
            resolved.append((stamp, source_url))
    if not resolved:
        raise ACPModelError("no downloadable GPM IMERG daily granules found for requested dates")
    if len({stamp for stamp, _ in resolved}) != len(resolved):
        raise ACPModelError("GPM IMERG query returned duplicate daily granules")
    return sorted(resolved)


def _gpm_window_precipitation_mm(path: Path, bbox: tuple[float, float, float, float]) -> float:
    """Read a GPM daily NetCDF4 file and return latitude-weighted monitor-window rain.

    GPM's daily `precipitation` unit is mm/day, so its numerical daily mean is
    also the daily accumulated depth.  The coordinate-order check prevents a
    silent lon/lat transpose when a collection version changes.
    """

    try:
        import h5py
        import numpy as np
    except ImportError as exc:  # pragma: no cover - runtime dependency
        raise ACPModelError("h5py and numpy are required to read GPM IMERG NetCDF4") from exc
    south, west, north, east = bbox
    if not (south < north and west < east):
        raise ACPModelError("GPM monitoring bbox must be south, west, north, east")
    with h5py.File(path, "r") as handle:
        if not {"lat", "lon", "precipitation"}.issubset(handle):
            raise ACPModelError("GPM IMERG file lacks lat, lon or precipitation")
        lat = np.asarray(handle["lat"][:], dtype=float)
        lon = np.asarray(handle["lon"][:], dtype=float)
        precipitation = np.asarray(handle["precipitation"][:], dtype=float)
    if precipitation.ndim != 3 or precipitation.shape[0] != 1:
        raise ACPModelError("GPM daily precipitation must have a single time dimension")
    lat_mask = (lat >= south) & (lat <= north)
    lon_mask = (lon >= west) & (lon <= east)
    if not lat_mask.any() or not lon_mask.any():
        raise ACPModelError("GPM monitoring bbox contains no grid cells")
    values = precipitation[0]
    if values.shape == (len(lon), len(lat)):
        window = values[lon_mask, :][:, lat_mask]
        latitude_weights = np.cos(np.deg2rad(lat[lat_mask]))
        weights = np.broadcast_to(latitude_weights, window.shape)
    elif values.shape == (len(lat), len(lon)):
        window = values[lat_mask, :][:, lon_mask]
        latitude_weights = np.cos(np.deg2rad(lat[lat_mask]))
        weights = np.broadcast_to(latitude_weights[:, None], window.shape)
    else:
        raise ACPModelError("GPM precipitation dimensions do not match latitude/longitude coordinates")
    valid = np.isfinite(window) & (window >= 0)
    if not valid.any():
        raise ACPModelError("GPM monitor window has no valid precipitation cells")
    return float(np.average(window[valid], weights=weights[valid]))


def fetch_gpm_imerg_daily_monitor(
    start_date: str,
    end_date: str,
    *,
    bbox: tuple[float, float, float, float] = GATUN_MONITORING_BBOX,
) -> list[DailySatellitePrecipitation]:
    """Collect short recent GPM observations into memory/temporary files only.

    Each source file is removed at the end of this call.  Derived daily means
    remain eligible for a local research report, with product and URL lineage.
    """

    token = _earthdata_token()
    resolved = _gpm_granules(start_date, end_date, token)
    with tempfile.TemporaryDirectory(prefix="gpm-imerg-") as directory:
        temporary_dir = Path(directory)

        def download(stamp: str, source_url: str) -> tuple[str, str, Path]:
            temporary_path = temporary_dir / f"{stamp}.nc4"
            try:
                with urllib.request.urlopen(_earthdata_request(source_url, token), timeout=180) as response:
                    temporary_path.write_bytes(response.read())
            except OSError as exc:
                raise ACPModelError(f"could not download GPM IMERG file for {stamp}") from exc
            return stamp, source_url, temporary_path

        # The daily files are roughly 30 MB each.  The GES DISC endpoint can
        # reject overlapping authenticated transfers, so this stays serial and
        # bounded to a short window rather than retrying or bulk-downloading.
        with ThreadPoolExecutor(max_workers=1) as executor:
            futures = [executor.submit(download, stamp, source_url) for stamp, source_url in resolved]
            downloaded = [future.result() for future in futures]
        # h5py's binary backend is not safely assumed to be thread-safe.  Only
        # the network transfer is concurrent; HDF5 decoding is deterministic.
        rows = [
            DailySatellitePrecipitation(
                observation_date=stamp,
                precipitation_mm=round(_gpm_window_precipitation_mm(path, bbox), 4),
                product_id=f"{GPM_IMERG_DAILY_SHORT_NAME}.{GPM_IMERG_DAILY_VERSION}",
                source_url=source_url,
            )
            for stamp, source_url, path in downloaded
        ]
    return sorted(rows, key=lambda row: row.observation_date)


def summarize_gpm_imerg_monitor(rows: list[DailySatellitePrecipitation]) -> dict[str, Any]:
    """Summarize observed GPM rainfall without rebranding it as a hydrology forecast."""

    if not rows:
        return {"status": "not_supplied"}
    ordered = sorted(rows, key=lambda row: row.observation_date)
    if len({row.observation_date for row in ordered}) != len(ordered):
        raise ACPModelError("GPM monitor contains duplicate observation dates")
    values = [row.precipitation_mm for row in ordered]
    return {
        "status": "observed_satellite_precipitation_local_only",
        "product_id": ordered[0].product_id,
        "monitoring_geometry": {
            "type": "rectangular_proxy_not_official_watershed_boundary",
            "bbox_south_west_north_east": list(GATUN_MONITORING_BBOX),
        },
        "observation_range": [ordered[0].observation_date, ordered[-1].observation_date],
        "observed_day_count": len(ordered),
        "total_precipitation_mm": round(sum(values), 3),
        "mean_precipitation_mm_per_day": round(statistics.fmean(values), 3),
        "daily_rows_local_only": [asdict(row) for row in ordered],
        "interpretation": (
            "recent GPM IMERG satellite observation for the declared rectangular monitoring window; "
            "not an official Gatun watershed total, not a water-level forecast, and not directly mixed "
            "into the NASA POWER-calibrated historical hydrology model without bias calibration"
        ),
    }


def compare_gpm_imerg_year_over_year(
    current_rows: list[DailySatellitePrecipitation], previous_year_rows: list[DailySatellitePrecipitation]
) -> dict[str, Any]:
    """Compare identical calendar days in GPM observations one year apart.

    The comparison is withheld rather than silently shortening either period;
    this matters when the latest GPM Late Run day is still delayed.
    """

    if not current_rows or not previous_year_rows:
        return {"status": "comparison_not_supplied"}
    current = sorted(current_rows, key=lambda row: row.observation_date)
    previous_by_date = {row.observation_date: row for row in previous_year_rows}
    expected_previous_dates = []
    for row in current:
        observed = date.fromisoformat(row.observation_date)
        try:
            expected_previous_dates.append(observed.replace(year=observed.year - 1).isoformat())
        except ValueError:
            return {"status": "withheld_leap_day_not_comparable"}
    if len(set(expected_previous_dates)) != len(expected_previous_dates):
        return {"status": "withheld_duplicate_comparison_dates"}
    if any(stamp not in previous_by_date for stamp in expected_previous_dates):
        return {
            "status": "withheld_missing_matching_previous_year_observation",
            "required_previous_dates": expected_previous_dates,
        }
    current_total = sum(row.precipitation_mm for row in current)
    previous_total = sum(previous_by_date[stamp].precipitation_mm for stamp in expected_previous_dates)
    difference = current_total - previous_total
    return {
        "status": "comparable_observed_same_calendar_days",
        "current_observation_range": [current[0].observation_date, current[-1].observation_date],
        "previous_year_observation_range": [expected_previous_dates[0], expected_previous_dates[-1]],
        "observed_day_count": len(current),
        "current_total_precipitation_mm": round(current_total, 3),
        "previous_year_total_precipitation_mm": round(previous_total, 3),
        "difference_mm": round(difference, 3),
        "change_pct": None if previous_total == 0 else round(100 * difference / previous_total, 2),
        "interpretation": (
            "same-calendar-day satellite precipitation comparison only; it is not a year-over-year "
            "change in canal traffic, lake storage, or a forecast"
        ),
    }


def research_source_catalog(*, c3s_ensemble_supplied: bool) -> list[dict[str, str]]:
    """Keep machine-readable provenance beside every local research report."""

    return [
        {
            "id": "nasa_gpm_imerg_late",
            "name": "NASA GPM IMERG daily Late Run",
            "role": "recent satellite precipitation monitor",
            "url": GPM_IMERG_COLLECTION_URL,
            "use_boundary": "derived local monitor only; raw NetCDF is deleted after processing",
        },
        {
            "id": "nasa_power_daily",
            "name": "NASA POWER Daily",
            "role": "long historical precipitation and land-evaporation sensitivity proxy",
            "url": "https://power.larc.nasa.gov/docs/services/api/temporal/daily/",
            "use_boundary": "EVLAND is not reservoir evaporation; model remains a sensitivity implementation",
        },
        {
            "id": "noaa_cpc_oni",
            "name": "NOAA Climate Prediction Center Oceanic Niño Index",
            "role": "lagged ENSO challenger variable",
            "url": "https://www.cpc.ncep.noaa.gov/data/indices/oni.ascii.txt",
            "use_boundary": "kept only when it improves the identical chronological holdout",
        },
        {
            "id": "munoz_2025",
            "name": "Muñoz et al. (2025), Drying of the Panama Canal in a Warming Climate",
            "role": "hydrology model design and validation basis",
            "url": MUÑOZ_2025_DOI,
            "use_boundary": "Python spline approximation, not the authors' exact R/mgcv implementation",
        },
        {
            "id": "copernicus_c3s_seasonal",
            "name": "Copernicus Climate Change Service seasonal forecasts",
            "role": "optional next-month precipitation/evaporation ensemble",
            "url": "https://cds.climate.copernicus.eu/datasets/seasonal-monthly-single-levels",
            "use_boundary": "used" if c3s_ensemble_supplied else "not used in this report; no external ensemble supplied",
        },
        {
            "id": "acp_local_only",
            "name": "Panama Canal Authority Gatun indicators and monthly operations summaries",
            "role": "local-only observed water level, operational constraints and transit labels",
            "url": ACP_ADVISORY_INDEX,
            "use_boundary": "do not commit, deploy or publicly redistribute ACP raw data or ACP-derived report until permission scope is confirmed",
        },
    ]


def extract_pdf_text(pdf_bytes: bytes) -> str:
    """Extract text locally; pypdf remains an optional runtime dependency."""

    try:
        from pypdf import PdfReader
    except ImportError as exc:  # pragma: no cover - depends on local extras
        raise ACPModelError("pypdf is required to parse an ACP PDF") from exc
    reader = PdfReader(io.BytesIO(pdf_bytes))
    if reader.is_encrypted:
        try:
            reader.decrypt("")
        except Exception as exc:
            raise ACPModelError("encrypted ACP PDF cannot be opened with an empty password") from exc
    return "\n".join(page.extract_text() or "" for page in reader.pages)


def _parse_acp_date(value: str) -> str:
    normalized = value.replace(".", "").strip()
    for pattern in ("%b %d, %Y", "%B %d, %Y"):
        try:
            return datetime.strptime(normalized, pattern).date().isoformat()
        except ValueError:
            pass
    raise ACPModelError(f"unrecognized ACP date: {value!r}")


def _first_float(patterns: Iterable[str], text: str, label: str) -> float | None:
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE | re.DOTALL)
        if match:
            return float(match.group(1))
    return None


def parse_gatun_dashboard_text(text: str, *, source_url: str = ACP_GATUN_DASHBOARD_PDF) -> GatunDashboardSnapshot:
    """Parse only explicitly labelled values from ACP's public dashboard PDF."""

    compact = re.sub(r"\s+", " ", text)
    date_match = re.search(
        r"Official Gatun Water Level\s+for\s+([A-Za-z]{3,9}\.?\s+\d{1,2},\s+\d{4})",
        compact,
        flags=re.IGNORECASE,
    )
    if not date_match:
        raise ACPModelError("official Gatun observation date not found")
    observation_date = _parse_acp_date(date_match.group(1))
    date_start = max(0, date_match.start() - 40)
    date_end = min(len(compact), date_match.end() + 80)
    local = compact[date_start:date_end]
    water_level_ft = _first_float(
        (r"([0-9]+(?:\.[0-9]+)?)\s*ft\s+Official Gatun Water Level",),
        local,
        "water level",
    )
    if water_level_ft is None:
        water_level_ft = _first_float(
            (r"Official Gatun Water Level.*?([0-9]+(?:\.[0-9]+)?)\s*ft",),
            local,
            "water level",
        )
    if water_level_ft is None:
        raise ACPModelError("official Gatun water level not found")

    surcharge = _first_float(
        (
            r"([0-9]+(?:\.[0-9]+)?)%\s+Variable Fresh Water Surcharge",
            r"Variable Fresh Water Surcharge.*?([0-9]+(?:\.[0-9]+)?)%",
        ),
        compact,
        "fresh water surcharge",
    )
    drafts = re.search(
        r"Official Maximum Draft\s+Neopanamax\s+Panamax\s+"
        r"([0-9]+(?:\.[0-9]+)?)\s*ft\s*([0-9]+(?:\.[0-9]+)?)\s*ft",
        compact,
        flags=re.IGNORECASE,
    )
    if not drafts:
        # ACP's visual layout can put the values above the title in the PDF
        # text stream even though the screen displays the title above them.
        drafts = re.search(
            r"Neopanamax\s+Panamax\s+([0-9]+(?:\.[0-9]+)?)\s*ft\s*"
            r"([0-9]+(?:\.[0-9]+)?)\s*ft\s+Official Maximum Draft",
            compact,
            flags=re.IGNORECASE,
        )
    projection = re.search(
        r"Last projection uploaded on:\s*([^\n]+?)(?:\s+Probable|\s+The estimated)",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return GatunDashboardSnapshot(
        observation_date=observation_date,
        water_level_ft=water_level_ft,
        fresh_water_surcharge_pct=surcharge,
        neopanamax_max_draft_ft=float(drafts.group(1)) if drafts else None,
        panamax_max_draft_ft=float(drafts.group(2)) if drafts else None,
        projection_uploaded_at=re.sub(r"\s+", " ", projection.group(1)).strip() if projection else None,
        source_url=source_url,
    )


def fetch_gatun_dashboard_snapshot(url: str = ACP_GATUN_DASHBOARD_PDF) -> GatunDashboardSnapshot:
    """Fetch and parse the latest official dashboard without a tracked raw cache."""

    return parse_gatun_dashboard_text(extract_pdf_text(fetch_public_pdf(url)), source_url=url)


def parse_gatun_projection_csv(text: str) -> list[GatunProjectionPoint]:
    """Parse the official ACP projection CSV, never treating it as observation."""

    start = text.find("projected_date,")
    if start < 0:
        raise ACPModelError("ACP projection CSV header not found")
    reader = csv.DictReader(io.StringIO(text[start:]))
    parsed = []
    for row in reader:
        try:
            projected = datetime.strptime(str(row["projected_date"]).strip(), "%m/%d/%Y").date().isoformat()
            value = float(str(row["projected_gatun_water_level"]).strip())
        except (KeyError, TypeError, ValueError) as exc:
            raise ACPModelError(f"invalid ACP Gatun projection row: {row}") from exc
        def optional(name: str) -> float | None:
            raw = row.get(name)
            return None if raw in (None, "") else float(str(raw).strip())
        parsed.append(GatunProjectionPoint(
            projected, value, optional("surcharge_pcent"), optional("max_neopanamax_draft_ft"),
            optional("max_panamax_draft_ft"),
        ))
    if not parsed:
        raise ACPModelError("ACP projection CSV has no points")
    return sorted(parsed, key=lambda item: item.projection_date)


def summarize_projection_month(points: list[GatunProjectionPoint], month: str) -> dict[str, Any]:
    """Summarize published ACP points for one calendar month without inference."""

    selected = [item for item in points if item.projection_date.startswith(month + "-")]
    if not selected:
        raise ACPModelError(f"ACP projection has no entries for {month}")
    return {
        "status": "official_acp_projection_not_model_output",
        "month": month,
        "day_count": len(selected),
        "mean_water_level_ft": round(statistics.fmean(item.water_level_ft for item in selected), 3),
        "minimum_water_level_ft": min(item.water_level_ft for item in selected),
        "maximum_water_level_ft": max(item.water_level_ft for item in selected),
        "neopanamax_draft_range_ft": [
            min(item.neopanamax_max_draft_ft for item in selected if item.neopanamax_max_draft_ft is not None),
            max(item.neopanamax_max_draft_ft for item in selected if item.neopanamax_max_draft_ft is not None),
        ],
        "panamax_draft_range_ft": [
            min(item.panamax_max_draft_ft for item in selected if item.panamax_max_draft_ft is not None),
            max(item.panamax_max_draft_ft for item in selected if item.panamax_max_draft_ft is not None),
        ],
    }


def parse_booking_slot_windows(text: str, *, source_url: str) -> list[BookingSlotWindow]:
    """Extract explicit booking-slot dates from an ACP Advisory.

    The parser intentionally accepts only sentences with a concrete start date
    and slots-per-day value.  It never interprets a chart or extrapolates an
    "until further notice" period into a synthetic end date.
    """

    compact = re.sub(r"\s+", " ", text)
    advisory_match = re.search(r"Advisory To Shipping No\.\s*([A-Z]-\d+-\d{4})", compact, re.I)
    advisory_id = advisory_match.group(1) if advisory_match else None
    month = r"(?:January|February|March|April|May|June|July|August|September|October|November|December)"
    partial_stamp = rf"(?P<month>{month})\s+(?P<day>\d{{1,2}})(?:,\s*(?P<year>\d{{4}}))?"
    end_stamp = rf"(?P<end_month>{month})\s+(?P<end_day>\d{{1,2}})(?:,\s*(?P<end_year>\d{{4}}))?"
    pattern = re.compile(
        rf"(?:from|For booking dates from|For booking dates beginning)\s+{partial_stamp}"
        rf"(?:\s*,?\s*to\s+{end_stamp}|\s*,?\s*and\s+until\s+further\s+notice)?"
        rf"[^.]*?(?:booking slots?\s+(?:will\s+(?:further\s+)?be\s+)?(?:reduced|increased)\s+to|"
        rf"number of booking slots?\s+(?:will\s+(?:further\s+)?be\s+)?(?:reduced|increased)\s+to)\s+(?P<slots>\d+)",
        re.IGNORECASE,
    )

    def resolve_date(match: re.Match[str], prefix: str, fallback_year: str | None) -> str:
        resolved_year = match.group(f"{prefix}year") or fallback_year
        if resolved_year is None:
            raise ACPModelError("ACP advisory omits a year needed to locate a booking-slot window")
        return _parse_acp_date(
            f"{match.group(f'{prefix}month')} {match.group(f'{prefix}day')}, {resolved_year}"
        )

    windows = []
    for match in pattern.finditer(compact):
        fallback_year = match.group("end_year") or match.group("year")
        windows.append(
            BookingSlotWindow(
                start_date=resolve_date(match, "", fallback_year),
                end_date=(resolve_date(match, "end_", fallback_year) if match.group("end_month") else None),
                slots_per_day=int(match.group("slots")),
                source_url=source_url,
                advisory_id=advisory_id,
            )
        )
    return windows


def discover_operations_summary_urls(index_html: str, *, base_url: str = ACP_ADVISORY_INDEX) -> list[str]:
    """Find official monthly operations PDFs without relying on advisory IDs."""

    candidates = re.findall(r'href=["\']([^"\']+\.pdf(?:\?[^"\']*)?)["\']', index_html, re.I)
    urls = []
    for raw in candidates:
        url = html.unescape(urljoin(base_url, raw))
        normalized = re.sub(r"[-_–—]+", " ", url).lower()
        if "operations summary" in normalized and ("monthly" in normalized or "montly" in normalized):
            urls.append(url)
    return sorted(set(urls))


def parse_monthly_operations_summary(text: str, *, source_url: str) -> MonthlyCanalOperations:
    """Parse only explicitly labelled statistics from an ACP monthly Advisory."""

    compact = re.sub(r"\s+", " ", text.replace("’", "'").replace("–", "-").replace("—", "-"))
    subject = re.search(
        r"(?:Monthly\s+)?Canal Operations Summary\s*-?\s*([A-Za-z]+)\s+(20\d{2})",
        compact,
        re.I,
    )
    if not subject:
        raise ACPModelError("monthly operations subject month not found")
    month_name, year = subject.group(1), subject.group(2)
    try:
        month = datetime.strptime(f"{month_name} {year}", "%B %Y").strftime("%Y-%m")
    except ValueError as exc:
        # One official filename/text uses the typo "Juny".
        if month_name.lower() == "juny":
            month = f"{year}-06"
        else:
            raise ACPModelError(f"unrecognized operations month: {month_name} {year}") from exc

    traffic_section = re.search(r"Traffic Statistics:(.*?)Oceangoing Transits:\s+Total", compact, re.I)
    if not traffic_section:
        raise ACPModelError(f"traffic statistics table not found for {month}")
    table = traffic_section.group(1)
    arrivals = re.search(r"Arrivals\s+([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)", table, re.I)
    traffic = re.search(r"Oceangoing Transits\s+([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)", table, re.I)
    water_time = re.search(r"Canal Waters Time \(hours\)\s+([0-9.]+)", table, re.I)
    transit_time = re.search(r"In-Transit Time \(hours\)\s+([0-9.]+)", table, re.I)
    if not all((arrivals, traffic, water_time, transit_time)):
        raise ACPModelError(f"one or more traffic rows not found for {month}")

    neo = re.search(
        r"Neopanamax Vessels \(107' beam and over\)\s+[0-9,]+\s+([0-9.]+)\s+[0-9.]+",
        compact,
        re.I,
    )
    booking_section = re.search(
        r"Booking Slots:\s+(.*?)(?:\* Does not include|\s+3\.\s+The following)", compact, re.I
    )
    available_values: list[float] = []
    used_values: list[float] = []
    if booking_section:
        for label in ("Neopanamax(?: Vessels)?", "(?:Supers|Large Vessels)", "Regular Vessels"):
            row = re.search(
                rf"{label}.*?\)\s+(?:Available\s+)?([0-9,]+)\*?\s+"
                rf"(?:Used\s+)?([0-9,]+)\*?(?:1|¹)?\s+(?:Percentage\s+)?([0-9.]+)",
                booking_section.group(1),
                re.I,
            )
            if row:
                available_values.append(float(row.group(1).replace(",", "")))
                used_values.append(float(row.group(2).replace(",", "")))
    available_total = sum(available_values) if len(available_values) == 3 else None
    used_total = sum(used_values) if len(used_values) == 3 else None
    utilization = None if not available_total else 100 * used_total / available_total
    advisory_match = re.search(r"Advisory To Shipping No\.\s*([A-Z]-?\d+-\d{4})", compact, re.I)
    return MonthlyCanalOperations(
        month=month,
        arrivals_daily_average=float(arrivals.group(1)),
        oceangoing_transits_daily_average=float(traffic.group(1)),
        oceangoing_transits_high=float(traffic.group(2)),
        oceangoing_transits_low=float(traffic.group(3)),
        canal_waters_time_hours=float(water_time.group(1)),
        in_transit_time_hours=float(transit_time.group(1)),
        neopanamax_transits_daily_average=float(neo.group(1)) if neo else None,
        booking_available_total=available_total,
        booking_used_total=used_total,
        booking_utilization_pct=utilization,
        source_url=source_url,
        advisory_id=advisory_match.group(1) if advisory_match else None,
    )


def fetch_monthly_operations_summaries(
    index_url: str = ACP_ADVISORY_INDEX, *, max_workers: int = 4
) -> tuple[list[MonthlyCanalOperations], list[dict[str, str]]]:
    """Fetch official PDFs in memory and return transparent parse failures."""

    urls = discover_operations_summary_urls(fetch_public_text(index_url), base_url=index_url)
    records: list[MonthlyCanalOperations] = []
    failures: list[dict[str, str]] = []

    def fetch_one(url: str) -> MonthlyCanalOperations:
        return parse_monthly_operations_summary(extract_pdf_text(fetch_public_pdf(url)), source_url=url)

    with ThreadPoolExecutor(max_workers=max(1, min(max_workers, 4))) as pool:
        futures = {pool.submit(fetch_one, url): url for url in urls}
        for future in as_completed(futures):
            url = futures[future]
            try:
                records.append(future.result())
            except Exception as exc:  # keep the entire batch auditable
                failures.append({"source_url": url, "error": str(exc)})
    by_month: dict[str, MonthlyCanalOperations] = {}
    for row in sorted(records, key=lambda item: (item.month, item.source_url)):
        by_month.setdefault(row.month, row)
    return list(by_month.values()), sorted(failures, key=lambda item: item["source_url"])


def load_monthly_history(path: Path) -> list[MonthlyHydrologyRecord]:
    """Load a user-authorized local history; no ACP raw data is committed."""

    required = {"month", "gatun_mean_ft", "precipitation_mm", "evaporation_mm"}
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows or not required.issubset(rows[0]):
        raise ACPModelError(f"history CSV needs columns: {sorted(required)}")
    parsed = []
    for row in rows:
        month = str(row["month"])
        try:
            datetime.strptime(month, "%Y-%m")
        except ValueError as exc:
            raise ACPModelError(f"invalid history month: {month}") from exc
        def optional(name: str) -> float | None:
            value = row.get(name)
            return None if value in (None, "") else float(value)
        parsed.append(
            MonthlyHydrologyRecord(
                month=month,
                gatun_mean_ft=float(row["gatun_mean_ft"]),
                precipitation_mm=float(row["precipitation_mm"]),
                evaporation_mm=float(row["evaporation_mm"]),
                oceangoing_transits_daily_average=optional("oceangoing_transits_daily_average"),
                booking_slots_per_day=optional("booking_slots_per_day"),
                neopanamax_max_draft_ft=optional("neopanamax_max_draft_ft"),
                panamax_max_draft_ft=optional("panamax_max_draft_ft"),
                oni_lag_6w=optional("oni_lag_6w"),
            )
        )
    parsed.sort(key=lambda item: item.month)
    if len({item.month for item in parsed}) != len(parsed):
        raise ACPModelError("history CSV contains duplicate months")
    return parsed


def load_acp_daily_gatun_history(path: Path) -> list[DailyGatunLevel]:
    """Read ACP's official daily Gatun CSV from a local, authorized path.

    The function deliberately does not download or cache the file. ACP's own
    current page restricts copying and derivative publication; callers retain
    the raw CSV outside the repository and decide their permission scope.
    """

    with path.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows or not {"DATE_LOG", "GATUN_LAKE_LEVEL(FEET)"}.issubset(rows[0]):
        raise ACPModelError("ACP daily history needs DATE_LOG and GATUN_LAKE_LEVEL(FEET) columns")
    parsed: list[DailyGatunLevel] = []
    for row in rows:
        try:
            stamp = datetime.strptime(str(row["DATE_LOG"]), "%Y-%m-%d").date().isoformat()
            level = float(str(row["GATUN_LAKE_LEVEL(FEET)"]).strip())
        except (TypeError, ValueError) as exc:
            raise ACPModelError(f"invalid ACP daily Gatun row: {row}") from exc
        parsed.append(DailyGatunLevel(stamp, level))
    if len({row.observation_date for row in parsed}) != len(parsed):
        raise ACPModelError("ACP daily history contains duplicate dates")
    return sorted(parsed, key=lambda item: item.observation_date)


def load_nasa_power_daily_meteorology(path: Path) -> list[DailyMeteorology]:
    """Read a local NASA POWER point response without calling the network.

    `PRECTOTCORR` is precipitation and `EVLAND` is land evaporation.  The
    latter is *not* the reservoir evaporation calculation in Muñoz et al.; it
    is a free, reproducible sensitivity proxy pending a paper-compatible
    ERA5-Land reservoir-evaporation preparation.
    """

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        parameters = payload["properties"]["parameter"]
        precipitation = parameters["PRECTOTCORR"]
        evaporation = parameters["EVLAND"]
    except (OSError, KeyError, TypeError, json.JSONDecodeError) as exc:
        raise ACPModelError("NASA POWER JSON needs properties.parameter.PRECTOTCORR and EVLAND") from exc
    if set(precipitation) != set(evaporation):
        raise ACPModelError("NASA POWER precipitation and evaporation dates do not align")
    parsed = []
    for stamp, rain in precipitation.items():
        try:
            observed = datetime.strptime(str(stamp), "%Y%m%d").date().isoformat()
            rain_value = float(rain)
            evap_value = float(evaporation[stamp])
        except (TypeError, ValueError) as exc:
            raise ACPModelError(f"invalid NASA POWER daily row: {stamp}") from exc
        if rain_value <= -900 or evap_value <= -900:
            continue
        parsed.append(DailyMeteorology(observed, rain_value, evap_value))
    if not parsed:
        raise ACPModelError("NASA POWER payload contains no valid meteorology rows")
    return sorted(parsed, key=lambda item: item.observation_date)


def aggregate_daily_hydrology_proxy(
    levels: list[DailyGatunLevel], meteorology: list[DailyMeteorology]
) -> list[MonthlyHydrologyRecord]:
    """Build a local monthly history from ACP levels and NASA POWER proxy data.

    A full calendar month needs at least 20 daily level readings and 20 daily
    meteorology readings. The common period only is used, and no missing day or
    month is imputed. This is suitable for a reproducible sensitivity/backtest,
    not for labelling the resulting model as identical to the paper's observed
    precipitation plus calculated reservoir evaporation specification.
    """

    levels_by_month: dict[str, list[float]] = {}
    weather_by_month: dict[str, list[DailyMeteorology]] = {}
    for item in levels:
        levels_by_month.setdefault(item.observation_date[:7], []).append(item.water_level_ft)
    for item in meteorology:
        weather_by_month.setdefault(item.observation_date[:7], []).append(item)
    records = []
    for month in sorted(set(levels_by_month) & set(weather_by_month)):
        observed_levels = levels_by_month[month]
        observed_weather = weather_by_month[month]
        if len(observed_levels) < 20 or len(observed_weather) < 20:
            continue
        records.append(MonthlyHydrologyRecord(
            month=month,
            gatun_mean_ft=statistics.fmean(observed_levels),
            precipitation_mm=sum(item.precipitation_mm for item in observed_weather),
            evaporation_mm=sum(item.evaporation_proxy_mm for item in observed_weather),
        ))
    if not records:
        raise ACPModelError("no complete common month in ACP/NASA daily inputs")
    return records


def parse_noaa_oni_text(text: str) -> dict[str, float]:
    """Parse NOAA CPC's ONI table into values keyed by centre month."""

    season_to_month = {
        "DJF": 1, "JFM": 2, "FMA": 3, "MAM": 4, "AMJ": 5, "MJJ": 6,
        "JJA": 7, "JAS": 8, "ASO": 9, "SON": 10, "OND": 11, "NDJ": 12,
    }
    parsed: dict[str, float] = {}
    for line in text.splitlines():
        match = re.match(r"\s*([A-Z]{3})\s+(\d{4})\s+[-0-9.]+\s+([-0-9.]+)\s*$", line)
        if not match or match.group(1) not in season_to_month:
            continue
        parsed[f"{int(match.group(2)):04d}-{season_to_month[match.group(1)]:02d}"] = float(match.group(3))
    if not parsed:
        raise ACPModelError("NOAA ONI table contains no season rows")
    return parsed


def attach_lagged_oni(
    records: list[MonthlyHydrologyRecord], oni_by_month: dict[str, float], *, lag_months: int = 2
) -> list[MonthlyHydrologyRecord]:
    """Attach only ONI values that would have been observable before the target month."""

    enriched = []
    for row in records:
        stamp = datetime.strptime(row.month, "%Y-%m")
        serial = stamp.year * 12 + stamp.month - 1 - lag_months
        lagged_month = f"{serial // 12:04d}-{serial % 12 + 1:02d}"
        enriched.append(replace(row, oni_lag_6w=oni_by_month.get(lagged_month)))
    return enriched


def load_monthly_climate_forecast_ensemble(path: Path) -> list[MonthlyClimateForecastMember]:
    """Load a local C3S/NMME/other ensemble after source-specific extraction."""

    required = {"source_id", "member_id", "month", "precipitation_mm", "evaporation_mm"}
    with path.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows or not required.issubset(rows[0]):
        raise ACPModelError(f"climate forecast CSV needs columns: {sorted(required)}")
    parsed = []
    for row in rows:
        try:
            datetime.strptime(str(row["month"]), "%Y-%m")
            oni = row.get("oni")
            parsed.append(MonthlyClimateForecastMember(
                source_id=str(row["source_id"]),
                member_id=str(row["member_id"]),
                month=str(row["month"]),
                precipitation_mm=float(row["precipitation_mm"]),
                evaporation_mm=float(row["evaporation_mm"]),
                oni=None if oni in (None, "") else float(oni),
            ))
        except (TypeError, ValueError) as exc:
            raise ACPModelError(f"invalid climate forecast member: {row}") from exc
    if len({(row.source_id, row.member_id, row.month) for row in parsed}) != len(parsed):
        raise ACPModelError("climate forecast ensemble contains duplicate source/member/month rows")
    return parsed


def aggregate_daily_gatun_to_monthly(
    levels: list[DailyGatunLevel],
    monthly_covariates: list[dict[str, str]],
) -> list[MonthlyHydrologyRecord]:
    """Join observed ACP levels to local monthly climate/operations covariates.

    Monthly covariates must be independently prepared from their licensed
    sources.  At least 20 observed daily levels are required for any month;
    sparse months are rejected rather than silently filled or interpolated.
    """

    by_month: dict[str, list[float]] = {}
    for row in levels:
        by_month.setdefault(row.observation_date[:7], []).append(row.water_level_ft)
    covariates = {str(row.get("month", "")): row for row in monthly_covariates}
    if not covariates:
        raise ACPModelError("monthly covariates are required")
    if len(covariates) != len(monthly_covariates):
        raise ACPModelError("monthly covariates contain duplicate months")

    def optional(row: dict[str, str], name: str) -> float | None:
        value = row.get(name)
        return None if value in (None, "") else float(value)

    merged: list[MonthlyHydrologyRecord] = []
    for month in sorted(covariates):
        try:
            datetime.strptime(month, "%Y-%m")
        except ValueError as exc:
            raise ACPModelError(f"invalid covariate month: {month}") from exc
        observed = by_month.get(month, [])
        if len(observed) < 20:
            raise ACPModelError(f"ACP level coverage below 20 daily observations for {month}")
        row = covariates[month]
        try:
            merged.append(MonthlyHydrologyRecord(
                month=month,
                gatun_mean_ft=statistics.fmean(observed),
                precipitation_mm=float(str(row["precipitation_mm"])),
                evaporation_mm=float(str(row["evaporation_mm"])),
                oceangoing_transits_daily_average=optional(row, "oceangoing_transits_daily_average"),
                booking_slots_per_day=optional(row, "booking_slots_per_day"),
                neopanamax_max_draft_ft=optional(row, "neopanamax_max_draft_ft"),
                panamax_max_draft_ft=optional(row, "panamax_max_draft_ft"),
                oni_lag_6w=optional(row, "oni_lag_6w"),
            ))
        except (KeyError, TypeError, ValueError) as exc:
            raise ACPModelError(f"invalid covariates for {month}") from exc
    return merged


def hydrology_design(records: list[MonthlyHydrologyRecord]) -> tuple[list[list[float]], list[float], list[str]]:
    """Build the paper-aligned monthly GAM design without filling missing months."""

    if any(
        datetime.strptime(records[index + 1].month, "%Y-%m").year * 12
        + datetime.strptime(records[index + 1].month, "%Y-%m").month
        != datetime.strptime(records[index].month, "%Y-%m").year * 12
        + datetime.strptime(records[index].month, "%Y-%m").month + 1
        for index in range(len(records) - 1)
    ):
        raise ACPModelError("history must be consecutive monthly observations; no imputation is allowed")
    features: list[list[float]] = []
    target: list[float] = []
    months: list[str] = []
    for index in range(11, len(records)):
        row = records[index]
        trailing = records[index - 11 : index + 1]
        features.append(
            [
                row.precipitation_mm,
                row.evaporation_mm,
                sum(item.precipitation_mm for item in trailing),
                sum(item.evaporation_mm for item in trailing),
            ]
        )
        target.append(row.gatun_mean_ft)
        months.append(row.month)
    return features, target, months


def _seasonal_baseline(train_target: list[float], train_months: list[str], test_months: list[str]) -> list[float]:
    by_month: dict[int, list[float]] = {}
    for value, stamp in zip(train_target, train_months):
        by_month.setdefault(datetime.strptime(stamp, "%Y-%m").month, []).append(value)
    fallback = statistics.fmean(train_target)
    return [
        statistics.fmean(by_month.get(datetime.strptime(stamp, "%Y-%m").month, [fallback]))
        for stamp in test_months
    ]


def fit_hydrology_gam(records: list[MonthlyHydrologyRecord]) -> dict[str, Any]:
    """Fit the paper-aligned additive hydrology model with an annual holdout.

    `mgcv::gam` with REML is the reference implementation published by Muñoz
    et al.  The deployable project deliberately avoids an R runtime, so this
    is an explicit Python additive-spline approximation.  It retains the four
    published covariates, 20 spline bases per term, 3x tail weighting, and a
    final 12-month chronological validation; it does not claim numerical
    identity with the authors' mgcv fit.
    """

    paper_features, paper_target, paper_months = hydrology_design(records)
    if len(paper_target) < MIN_HYDROLOGY_MONTHS:
        return {
            "status": "insufficient_authorized_history",
            "forecast_use": "withheld",
            "sample_count": len(paper_target),
            "minimum_sample_count": MIN_HYDROLOGY_MONTHS,
            "required_columns": ["gatun_mean_ft", "precipitation_mm", "evaporation_mm"],
        }
    try:
        import numpy as np
        from sklearn.linear_model import Ridge
        from sklearn.pipeline import make_pipeline
        from sklearn.preprocessing import SplineTransformer, StandardScaler
    except ImportError as exc:
        return {
            "status": "dependency_missing",
            "forecast_use": "withheld",
            "missing_dependency": str(exc),
        }
    aligned = [
        (features, target, month, row.oni_lag_6w)
        for features, target, month, row in zip(paper_features, paper_target, paper_months, records[11:])
        if row.oni_lag_6w is not None
    ]
    if len(aligned) >= MIN_HYDROLOGY_MONTHS:
        paper_features = [row[0] for row in aligned]
        paper_target = [row[1] for row in aligned]
        paper_months = [row[2] for row in aligned]

    def backtest(name: str, features: list[list[float]], target: list[float], months: list[str]) -> dict[str, Any]:
        split = len(target) - 12
        x_train, x_test = np.asarray(features[:split]), np.asarray(features[split:])
        y_train, y_test = np.asarray(target[:split]), np.asarray(target[split:])
        low_threshold, high_threshold = np.quantile(y_train, [0.1, 0.9])
        sample_weight = np.where((y_train < low_threshold) | (y_train > high_threshold), 3.0, 1.0)
        model = make_pipeline(
            SplineTransformer(n_knots=20, degree=3, extrapolation="linear"),
            StandardScaler(),
            Ridge(alpha=2.0),
        )
        model.fit(x_train, y_train, ridge__sample_weight=sample_weight)
        predicted = model.predict(x_test)
        baseline = _seasonal_baseline(target[:split], months[:split], months[split:])
        model_mae = float(np.mean(np.abs(y_test - predicted)))
        baseline_mae = statistics.fmean(abs(actual - expected) for actual, expected in zip(y_test, baseline))
        improvement = None if baseline_mae == 0 else 1 - model_mae / baseline_mae
        residual_sigma = float(np.sqrt(np.mean((y_test - predicted) ** 2)))
        return {
            "candidate_id": name,
            "sample_count": len(target),
            "train_count": len(y_train),
            "test_count": len(y_test),
            "holdout_start_month": months[split],
            "model_mae_ft": round(model_mae, 4),
            "seasonal_baseline_mae_ft": round(baseline_mae, 4),
            "holdout_rmse_ft": round(residual_sigma, 4),
            "approximate_95pct_prediction_half_width_ft": round(1.96 * residual_sigma, 4),
            "improvement_vs_seasonal_baseline": round(improvement, 4) if improvement is not None else None,
        }

    candidates = [backtest("paper_gam", paper_features, paper_target, paper_months)]
    if len(aligned) >= MIN_HYDROLOGY_MONTHS:
        enso_features = [row[0] + [float(row[3])] for row in aligned]
        candidates.append(backtest("paper_gam_plus_lagged_oni", enso_features, paper_target, paper_months))
    selected = min(candidates, key=lambda item: item["model_mae_ft"])
    improvement = selected["improvement_vs_seasonal_baseline"]
    return {
        "status": "backtested",
        "method": "candidate-selected monthly additive spline GAM: paper four-term specification versus optional lagged-ONI challenger; same final 12-month chronological holdout",
        "research_basis": MUÑOZ_2025_DOI,
        "selected_candidate": selected["candidate_id"],
        **{key: value for key, value in selected.items() if key != "candidate_id"},
        "candidate_backtests": candidates,
        "forecast_use": "research_only" if improvement is not None and improvement >= 0.05 else "withheld",
        "publication_gate": "selected candidate requires at least 5% holdout MAE improvement versus seasonal baseline; lagged ONI is retained only if it improves the identical holdout; no model may override ACP Advisories",
    }


def forecast_hydrology_ensemble(
    records: list[MonthlyHydrologyRecord], members: list[MonthlyClimateForecastMember]
) -> dict[str, Any]:
    """Project the next monthly Gatun level from an external climate ensemble."""

    backtest = fit_hydrology_gam(records)
    if backtest.get("forecast_use") != "research_only":
        return {"status": "withheld_failed_hydrology_backtest", "forecast_use": "withheld"}
    target_months = sorted({member.month for member in members})
    if len(target_months) != 1:
        return {"status": "one_target_month_required", "forecast_use": "withheld", "months": target_months}
    latest = datetime.strptime(records[-1].month, "%Y-%m")
    serial = latest.year * 12 + latest.month
    expected = f"{serial // 12:04d}-{serial % 12 + 1:02d}"
    if target_months[0] != expected:
        return {
            "status": "forecast_must_be_next_consecutive_month",
            "forecast_use": "withheld",
            "latest_history_month": records[-1].month,
            "target_month": target_months[0],
        }
    try:
        import numpy as np
        from sklearn.linear_model import Ridge
        from sklearn.pipeline import make_pipeline
        from sklearn.preprocessing import SplineTransformer, StandardScaler
    except ImportError as exc:
        return {"status": "dependency_missing", "forecast_use": "withheld", "missing_dependency": str(exc)}
    paper_features, target, months = hydrology_design(records)
    selected = backtest["selected_candidate"]
    if selected == "paper_gam_plus_lagged_oni":
        aligned = [
            (features + [float(row.oni_lag_6w)], value, month)
            for features, value, month, row in zip(paper_features, target, months, records[11:])
            if row.oni_lag_6w is not None
        ]
        paper_features = [row[0] for row in aligned]
        target = [row[1] for row in aligned]
        if any(member.oni is None for member in members):
            return {"status": "selected_enso_model_requires_forecast_oni", "forecast_use": "withheld"}
    train_x = np.asarray(paper_features)
    train_y = np.asarray(target)
    low, high = np.quantile(train_y, [0.1, 0.9])
    weights = np.where((train_y < low) | (train_y > high), 3.0, 1.0)
    model = make_pipeline(
        SplineTransformer(n_knots=20, degree=3, extrapolation="linear"), StandardScaler(), Ridge(alpha=2.0)
    )
    model.fit(train_x, train_y, ridge__sample_weight=weights)
    trailing = records[-11:]
    forecast_features = []
    for member in members:
        features = [
            member.precipitation_mm,
            member.evaporation_mm,
            sum(row.precipitation_mm for row in trailing) + member.precipitation_mm,
            sum(row.evaporation_mm for row in trailing) + member.evaporation_mm,
        ]
        if selected == "paper_gam_plus_lagged_oni":
            features.append(float(member.oni))
        forecast_features.append(features)
    predictions = model.predict(np.asarray(forecast_features))
    by_source = {}
    for source_id in sorted({member.source_id for member in members}):
        values = [
            float(prediction) for member, prediction in zip(members, predictions) if member.source_id == source_id
        ]
        by_source[source_id] = {
            "member_count": len(values),
            "p10_water_level_ft": round(float(np.quantile(values, 0.1)), 3),
            "median_water_level_ft": round(float(np.quantile(values, 0.5)), 3),
            "p90_water_level_ft": round(float(np.quantile(values, 0.9)), 3),
        }
    half_width = float(backtest["approximate_95pct_prediction_half_width_ft"])
    pooled = [float(value) for value in predictions]
    return {
        "status": "research_only_external_ensemble_forecast",
        "forecast_use": "research_only",
        "target_month": target_months[0],
        "selected_hydrology_candidate": selected,
        "sources": by_source,
        "pooled_member_count": len(pooled),
        "pooled_median_water_level_ft": round(float(np.quantile(pooled, 0.5)), 3),
        "conservative_95pct_range_ft": [
            round(float(np.quantile(pooled, 0.1)) - half_width, 3),
            round(float(np.quantile(pooled, 0.9)) + half_width, 3),
        ],
        "warning": "multi-source pooling weights individual members; compare source-level ranges before use",
    }


def fit_transit_response(
    hydrology: list[MonthlyHydrologyRecord],
    operations: list[MonthlyCanalOperations],
    published_projection: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Backtest a leakage-controlled monthly ACP transit response model.

    Current-month water level and *available* booking slots may be known from
    ACP forecasts/notices. Demand and congestion variables use the preceding
    month only. Current-month used slots, arrivals and waiting time are never
    predictors because they would not exist at forecast issue time.
    """

    hydro_by_month = {row.month: row for row in hydrology}
    ordered = sorted(operations, key=lambda item: item.month)
    x: list[list[float]] = []
    y: list[float] = []
    months: list[str] = []
    persistence: list[float] = []
    for previous, current in zip(ordered, ordered[1:]):
        prev_stamp = datetime.strptime(previous.month, "%Y-%m")
        curr_stamp = datetime.strptime(current.month, "%Y-%m")
        if curr_stamp.year * 12 + curr_stamp.month != prev_stamp.year * 12 + prev_stamp.month + 1:
            continue
        hydro = hydro_by_month.get(current.month)
        previous_hydro = hydro_by_month.get(previous.month)
        if (
            hydro is None or previous_hydro is None
            or current.booking_available_total is None or previous.booking_available_total is None
        ):
            continue
        days = calendar.monthrange(curr_stamp.year, curr_stamp.month)[1]
        previous_days = calendar.monthrange(prev_stamp.year, prev_stamp.month)[1]
        month_number = curr_stamp.month
        x.append([
            hydro.gatun_mean_ft - previous_hydro.gatun_mean_ft,
            current.booking_available_total / days - previous.booking_available_total / previous_days,
            previous.arrivals_daily_average - previous.oceangoing_transits_daily_average,
            (previous.booking_utilization_pct if previous.booking_utilization_pct is not None else 100.0) - 100.0,
            previous.canal_waters_time_hours,
            hydro.gatun_mean_ft,
            math.sin(2 * math.pi * month_number / 12),
            math.cos(2 * math.pi * month_number / 12),
        ])
        y.append(current.oceangoing_transits_daily_average)
        months.append(current.month)
        persistence.append(previous.oceangoing_transits_daily_average)
    if len(y) < MIN_TRANSIT_MONTHS:
        return {
            "status": "insufficient_authorized_operations_history",
            "forecast_use": "withheld",
            "sample_count": len(y),
            "minimum_sample_count": MIN_TRANSIT_MONTHS,
            "required_columns": [
                "monthly Gatun mean",
                "official monthly available booking slots",
                "lagged official transits/arrivals/booking utilization/canal waters time",
            ],
        }
    try:
        import numpy as np
        from sklearn.linear_model import Ridge
        from sklearn.linear_model import HuberRegressor
        from sklearn.pipeline import make_pipeline
        from sklearn.ensemble import RandomForestRegressor
        from sklearn.preprocessing import StandardScaler
    except ImportError as exc:
        return {"status": "dependency_missing", "forecast_use": "withheld", "missing_dependency": str(exc)}
    split = len(y) - 12
    train_x, test_x = np.asarray(x[:split]), np.asarray(x[split:])
    train_y, test_y = np.asarray(y[:split]), np.asarray(y[split:])
    delta_y = np.asarray([actual - prior for actual, prior in zip(y, persistence)])
    train_delta = delta_y[:split]
    candidates = {
        "ridge": make_pipeline(StandardScaler(), Ridge(alpha=2.0)),
        "huber": make_pipeline(StandardScaler(), HuberRegressor(epsilon=1.5, alpha=0.5, max_iter=1000)),
        "random_forest": RandomForestRegressor(
            n_estimators=400, min_samples_leaf=3, max_features=0.75, random_state=42
        ),
    }
    candidate_metrics = []
    for candidate_id, model in candidates.items():
        model.fit(train_x, train_delta)
        predicted = np.asarray(persistence[split:]) + model.predict(test_x)
        residuals = [abs(float(actual - estimate)) for actual, estimate in zip(test_y, predicted)]
        candidate_metrics.append({
            "candidate_id": candidate_id,
            "mae_transits_per_day": round(statistics.fmean(residuals), 4),
            "rmse_transits_per_day": round(float(np.sqrt(np.mean((test_y - predicted) ** 2))), 4),
            "empirical_p90_absolute_error": round(float(np.quantile(residuals, 0.9)), 4),
        })
    selected = min(candidate_metrics, key=lambda item: item["mae_transits_per_day"])
    seasonal = _seasonal_baseline(y[:split], months[:split], months[split:])
    seasonal_mae = statistics.fmean(abs(actual - estimate) for actual, estimate in zip(y[split:], seasonal))
    persistence_mae = statistics.fmean(
        abs(actual - estimate) for actual, estimate in zip(y[split:], persistence[split:])
    )
    baseline_mae = min(seasonal_mae, persistence_mae)
    model_mae = selected["mae_transits_per_day"]
    improvement = None if baseline_mae == 0 else 1 - model_mae / baseline_mae
    forecast_use = "research_only" if improvement is not None and improvement >= 0.05 else "withheld"
    forecast = None
    if forecast_use == "research_only" and published_projection:
        target_month = str(published_projection.get("month", ""))
        latest = ordered[-1]
        target_stamp = datetime.strptime(target_month, "%Y-%m")
        latest_stamp = datetime.strptime(latest.month, "%Y-%m")
        gap = target_stamp.year * 12 + target_stamp.month - (latest_stamp.year * 12 + latest_stamp.month)
        if 1 <= gap <= 2 and latest.booking_available_total is not None:
            selected_model = candidates[selected["candidate_id"]]
            selected_model.fit(np.asarray(x), delta_y)
            state_transits = latest.oceangoing_transits_daily_average
            queue_pressure = latest.arrivals_daily_average - latest.oceangoing_transits_daily_average
            state_water = hydro_by_month[latest.month].gatun_mean_ft
            latest_days = calendar.monthrange(latest_stamp.year, latest_stamp.month)[1]
            slots_per_day = latest.booking_available_total / latest_days
            path = []
            for step in range(1, gap + 1):
                serial = latest_stamp.year * 12 + latest_stamp.month - 1 + step
                month = f"{serial // 12:04d}-{serial % 12 + 1:02d}"
                stamp = datetime.strptime(month, "%Y-%m")
                if month == target_month:
                    water = float(published_projection["mean_water_level_ft"])
                elif month in hydro_by_month:
                    water = hydro_by_month[month].gatun_mean_ft
                else:
                    break
                features = np.asarray([[
                    water - state_water,
                    0.0,
                    queue_pressure,
                    (latest.booking_utilization_pct if latest.booking_utilization_pct is not None else 100.0) - 100.0,
                    latest.canal_waters_time_hours,
                    water,
                    math.sin(2 * math.pi * stamp.month / 12),
                    math.cos(2 * math.pi * stamp.month / 12),
                ]])
                state_transits += float(selected_model.predict(features)[0])
                state_water = water
                path.append({"month": month, "point_transits_per_day": round(state_transits, 3)})
            if len(path) == gap:
                p90 = float(selected["empirical_p90_absolute_error"]) * math.sqrt(gap)
                forecast = {
                    "status": "research_scenario_with_carried_forward_operations",
                    "target_month": target_month,
                    "point_transits_per_day": path[-1]["point_transits_per_day"],
                    "empirical_p90_range_transits_per_day": [
                        round(max(0.0, path[-1]["point_transits_per_day"] - p90), 3),
                        round(path[-1]["point_transits_per_day"] + p90, 3),
                    ],
                    "recursive_path": path,
                    "assumptions": [
                        f"latest official monthly operations label is {latest.month}",
                        f"available booking slots per day carried forward at {slots_per_day:.3f}",
                        "latest official queue pressure, booking utilization and Canal Waters Time carried forward",
                        "target water level uses ACP's published projection; intermediate current month uses observed partial-month mean when available",
                    ],
                    "not_for_publication": True,
                }
    return {
        "status": "backtested",
        "method": "leakage-controlled monthly-change response: ridge, robust Huber and conservative random forest predict change from persistence using Gatun/available-slot changes plus lagged queue pressure and congestion; final 12-month holdout",
        "sample_count": len(y),
        "train_count": split,
        "test_count": len(y) - split,
        "holdout_start_month": months[split],
        "selected_candidate": selected["candidate_id"],
        "candidate_backtests": candidate_metrics,
        "model_mae_transits_per_day": model_mae,
        "seasonal_baseline_mae_transits_per_day": round(seasonal_mae, 4),
        "persistence_baseline_mae_transits_per_day": round(persistence_mae, 4),
        "best_baseline_mae_transits_per_day": round(baseline_mae, 4),
        "improvement_vs_best_baseline": round(improvement, 4) if improvement is not None else None,
        "forecast_use": forecast_use,
        "forecast": forecast,
        "publication_gate": "requires at least 5% holdout MAE improvement versus the better of seasonal and persistence baselines; no current-month demand leakage",
    }


def build_local_acp_report(
    dashboard: GatunDashboardSnapshot,
    *,
    history: list[MonthlyHydrologyRecord] | None = None,
    advisory_windows: list[BookingSlotWindow] | None = None,
    published_projection: dict[str, Any] | None = None,
    monthly_operations: list[MonthlyCanalOperations] | None = None,
    operations_failures: list[dict[str, str]] | None = None,
    climate_forecast_members: list[MonthlyClimateForecastMember] | None = None,
    satellite_precipitation: list[DailySatellitePrecipitation] | None = None,
    previous_year_satellite_precipitation: list[DailySatellitePrecipitation] | None = None,
) -> dict[str, Any]:
    """Build a transparent local report with withheld forecasts by default."""

    history = history or []
    monthly_operations = monthly_operations or []
    climate_forecast_members = climate_forecast_members or []
    satellite_precipitation = satellite_precipitation or []
    previous_year_satellite_precipitation = previous_year_satellite_precipitation or []
    return {
        "status": "local_research_only_not_deployable",
        "data_boundary": {
            "raw_acp_documents": "local temporary cache only; never committed or deployed by this module",
            "current_dashboard": asdict(dashboard),
            "history_source_status": "authorized_local_history_loaded" if history else "history_not_supplied",
            "advisory_window_count": len(advisory_windows or []),
            "published_acp_projection": published_projection,
            "monthly_operations_count": len(monthly_operations),
            "monthly_operations_range": (
                [min(row.month for row in monthly_operations), max(row.month for row in monthly_operations)]
                if monthly_operations else None
            ),
            "monthly_operations_parse_failures": operations_failures or [],
            "monthly_operations_rows_local_only": [asdict(row) for row in monthly_operations],
            "gpm_imerg_recent_monitor": summarize_gpm_imerg_monitor(satellite_precipitation),
            "gpm_imerg_year_over_year": compare_gpm_imerg_year_over_year(
                satellite_precipitation, previous_year_satellite_precipitation
            ),
        },
        "data_sources": research_source_catalog(c3s_ensemble_supplied=bool(climate_forecast_members)),
        "model_layers": {
            "hydrology": fit_hydrology_gam(history) if history else {
                "status": "history_required",
                "forecast_use": "withheld",
                "research_basis": MUÑOZ_2025_DOI,
            },
            "hydrology_forecast_ensemble": (
                forecast_hydrology_ensemble(history, climate_forecast_members)
                if history and climate_forecast_members
                else {"status": "external_climate_ensemble_not_supplied", "forecast_use": "withheld"}
            ),
            "operations": {
                "status": "official_advisory_overrides_statistical_inference",
                "windows": [asdict(item) for item in advisory_windows or []],
            },
            "transits": fit_transit_response(history, monthly_operations, published_projection) if history and monthly_operations else {
                "status": "hydrology_and_monthly_operations_history_required",
                "forecast_use": "withheld",
            },
        },
        "publication_rule_ko": (
            "수위만으로 통항량·DWT·봉쇄율을 산출하지 않는다. 과거 수문·ACP 운영·공식 통항 라벨의 "
            "시간순 백테스트가 계절 기준선보다 개선될 때만 연구용 예측을 검토한다."
        ),
    }
